### ISSUE TITLE
Google will not stay signed in after latest user.js [solved: duplicate of 1339, 1311, 1291, 1278, 1223: add site exceptions]

### ISSUE THREAD

**Issue by DanitiKain** [arkenfox/user.js#1341] opened 2022-01-21 16:25 UTC
v. 96.0.01
latest updated user.js

Firefox Profile for Google:

I have had this profile across many machines and after recent run of update.bat for user.js if I close the browser it no longer keeps me signed in for google. In past I had to put these settings in the user-overrides to get things to work via google and allow sign-in via google on other sites as well.  Can you please provide any suggestions that might lead me in the right direction for anything new that would be affecting this. 

user-overrides.js:
```js
user_pref("browser.startup.page", 3);
user_pref("browser.privatebrowsing.autostart",false);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.cpd.cookies", false);
user_pref("browser.sessionstore.privacy_level", 0);
user_pref("network.cookie.cookieBehavior", 0);
user_pref("network.cookie.thirdparty.sessionOnly", false);
user_pref("network.cookie.thirdparty.nonsecureSessionOnly", false);
user_pref("privacy.clearOnShutdown.cache", false);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.clearOnShutdown.history", false); // Browsing & Download History
user_pref("privacy.clearOnShutdown.offlineApps", false); // Offline Website Data
user_pref("privacy.clearOnShutdown.sessions", false); // Active Logins
user_pref("privacy.cpd.history", false; 
ser_pref("privacy.cpd.sessions", false);
user_pref("privacy.clearOnShutdown.openWindows", false);
```

**Comment by rusty-snake** [comment] 2022-01-21 16:28
#1080 :small_red_triangle_down: enable session restore

> to keep cookies for selected sites, add site exceptions as `Allow`, see 2801

**Comment by DanitiKain** [comment] 2022-01-22 00:36
I took those settings out and when I close and go back it doesn't work.

I am signed out of the account.

**Comment by DanitiKain** [comment] 2022-01-22 00:37
Now on v96.0.2 and latest user.js as well.

**Comment by Thorin-Oakenpants** [comment] 2022-01-22 02:30
i assume `ser_pref("privacy.cpd.sessions", false);` is a typo (missing the u in user)

AF makes all cookies + site data as session only (for now this is the cookie behavior pref) - _**we did this change several versions ago**_ . Previously it was set to delete all cookies and site data on close and you couldn't add exceptions. Not sanitizing between sessions is not good hygiene. The new way allows sanitizing with exceptions

What you are trying to do is not sanitize anything in order to keep a few cookies. _**You do not need to change any prefs in order to keep some cookies**_

What you do is add sites as site exceptions. You can do this in two ways
- visit the site, go control-i, go to permissions tab, change cookies from default to `Allow`
- go to Settings> Privacy & Security > Cookies & Site Data > Manage Exceptions and add them manually

AF used FPI in earlier versions, so exceptions required a different syntax. In v96+ we are no longer using FPI - see #1281 - so exceptions need to be updated

If you are logging in cross-domain, you will need to add exceptions for both sites

**Comment by DanitiKain** [comment] 2022-01-22 05:20
This worked thanks. Best way I found was use the developer options and watch the network traffic and see what domains you think might need to be white listed. Thanks everyone for all the help.

**Comment by CGYoung1040** [comment] 2022-02-02 09:00
Adding site exception via CTRL-I works for almost every website except for google/youtube. no matter what I try they always log me out after closing firefox.

overrides include:
user_pref("media.eme.enabled", true);
user_pref("network.http.referer.XOriginPolicy", 0);
user_pref("ui.systemUsesDarkTheme", 1);
user_pref("signon.rememberSignons", false);

...and some more supplemental settings from 12bytes.org: https://codeberg.org/12bytes.org/firefox-user.js-supplement

I even tried turning off RFP but to no avail. Please help me figure this out

**Comment by rusty-snake** [comment] 2022-02-02 09:05
So you set `user_pref("privacy.clearOnShutdown.offlineApps", true);` in your overrides?

**Comment by CGYoung1040** [comment] 2022-02-02 10:28
No, I commented that one out. Also I tried using the user.js as is without any overrides and I still can't get Google/Youtube to keep being logged in.

**Comment by rusty-snake** [comment] 2022-02-02 10:35
> Also I tried using the user.js as is without any overrides and I still can't get Google/Youtube to keep me logged in.

In a new profile?

**Comment by CGYoung1040** [comment] 2022-02-02 10:55
Admittedly I didn't before but I just tried again with a new profile and without any extensions and still same issue

**Comment by Thorin-Oakenpants** [comment] 2022-02-02 14:21
> No, I commented that one out

just a nit here
- commenting out prefs does not reset them - https://github.com/arkenfox/user.js/wiki/2.1-User.js#-usage
- always use overrides : https://github.com/arkenfox/user.js/wiki/3.1-Overrides

**Comment by Thorin-Oakenpants** [comment] 2022-02-02 14:27
@CGYoung1040 You do not need to override any prefs to keep logins
- see https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common]#-keep-logins

> works for almost every website except for Google/YouTube

So you are adding both sites, right? Can you list the actual entries you are adding to `Manage Exceptions` (either manually or via Ctrl-I)

I can't test since I don't have accounts

**Comment by CGYoung1040** [comment] 2022-02-02 15:56
As I've previously said, I've used overrides and of course prefsCleaner, so by commenting out something in the user-overrides.js, it should indeed reset that value when running updater.bat. Also I've tried using no overrides at all and just the base user.js from your repo in a new profile without any extensions and the problem still persists. Yes, I've added both YouTube and Google to the exceptions. The actual entries are `https://www.youtube.com` and `https://www.google.com` and I even tried adding `https://www.consent.youtube.com`. 

I despise google as well but unfortunately I don't really see a viable way of avoiding YouTube.

**Comment by GlassGruber** [comment] 2022-02-02 23:22
Do you have any non Windows antivirus installed? Can be pretty nasty software.

https://support.google.com/youtube/thread/111833618/youtube-is-pretty-broken-on-firefox-currently?hl=en&msgid=111835297

**Comment by CGYoung1040** [comment] 2022-02-03 07:59
I'm running a fresh version of Ubuntu, so no.

**Comment by Thorin-Oakenpants** [comment] 2022-02-03 08:38
> As I've previously said

Yes, I know you said you tried a new profile with and w/out the user.js, etc, but I don't want any readers getting the wrong idea

Reopening so as to work out what is going on here: Test 1
- New profile, change to ETP Strict. Visit YT, login with google account. Close FF
- Inspect cookies.sqlite - what are the entries
- Start FF, visit YT - are you auto logged in?

**Comment by CGYoung1040** [comment] 2022-02-03 10:23
> with and w/out the user.js
no, I've always used the arkenfox user.js with and without my own user-overrides.js 

Test 1:
- new profile, fresh user.js with ETP Strict
- YT/Google login, added cookie site exception using CTRL-I
- close FF
- cookies.sqlite entries are listed in the attached .csv (I wasn’t really sure how to inspect, I’ve used DB Browser)
- restart FF and I’m logged out again. Don’t really know what you mean by auto-logged in (isn't the fact that I'm not auto logged in exactly my problem?)
- I’ve also attached a screenshot of the console output when I’m logged into YT

Thanks for reopening the ticket and helping me!

[moz_cookies.csv](https://github.com/arkenfox/user.js/files/7993611/moz_cookies.csv)
![console](https://user-images.githubusercontent.com/98876691/152323957-2679486d-884e-4ee2-979a-00d79b9d43eb.png)

**Comment by CGYoung1040** [comment] 2022-02-03 10:41
Sorry for the noob question but did I just doxx myself or reveal my login info/password in any way by showing those cookies?

**Comment by Thorin-Oakenpants** [comment] 2022-02-03 11:22
Test 1 was a new profile with ETP Strict. No user.js. I want to make sure that dFPI is not at fault. When that test is done, then I was going to ask for a couple of about:config changes

Think about it. Test FF with zero changes - it works. So now turn on ETP Strict. Does it work? If yes then keep testing, if not, then you have your answer (as to the cause)

No, you didn't dox yourself, and console info is important for when things don' work - but I wanted the list of the cookies in cookies.sqlite (don't show IDs etc) - so I would know all the possible eTLD+1's involved. If you don't know how to do that (sqlite), , or follow precise test steps, then IDK, I give up

**Comment by Thorin-Oakenpants** [comment] 2022-02-03 12:08
The first thing that springs to mind is that Smart Blocking's heuristics are session only - but I need to check that - so you would still to click a button, and on smart block sites using SSO auto-login isn't a thing

Secondly, we could create a list somewhere - in the override recipe issue probably - of the pair of sites to add exceptions too: e.g. I think instagram is IG and fb.net or something

Thirdly, do we actually need to add the parent (e.g gmail) vs the SSO (google) for it to work

**Comment by rusty-snake** [comment] 2022-02-03 12:12
Opener Heuristics is for 30 days and Redirect Heuristics is for 15 minutes.

https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning

**Comment by Thorin-Oakenpants** [comment] 2022-02-03 12:26
We should add that info to the user.js

**Comment by CGYoung1040** [comment] 2022-02-03 12:33
> If you don't know how to do that (sqlite), , or follow precise test steps, then IDK, I give up

I was trying to follow your steps but I'm not much of an expert here so apologies for that. My thinking was that you wanted to find out why the AK user.js didn't let FF store cookies in that particular instance.

> Test 1 was a new profile with ETP Strict. No user.js. I want to make sure that dFPI is not at fault.

Attached is an updated list of cookies of a new profile in ETP Strict w/out the user.js. Again, apologies if this isn't the format that you wanted but I honestly don't know what's important here and what's not.

[moz_cookies.csv](https://github.com/arkenfox/user.js/files/7994482/moz_cookies.csv)

**Comment by Thorin-Oakenpants** [comment] 2022-02-03 12:40
yikes, I only needed the domains :) I edited your last post

so we have
```
.google.com
accounts.google.com
.youtube.com
google.ch
ogs.google.com
```

So now try in your main firefox profile
- go to https://accounts.google.com/
- go ctrl-I > permissions > cookies > Allow

what you said earlier
> The actual entries are `https://www.youtube.com` and `https://www.google.com` ...

**Comment by Thorin-Oakenpants** [comment] 2022-02-03 12:43
> My thinking was that you wanted to find out why the AK user.js didn't let FF store cookies in that particular instance

Oh no, I know it's storing the cookies you add exceptions for, I wanted to get the list of domains (and rule out ETP Strict doing something)

anyway, try adding `https://accounts.google.com` - if that works, great

then test if you actually need `https://www.google.com`

**Comment by CGYoung1040** [comment] 2022-02-03 12:54
> anyway, try adding `https://accounts.google.com` - if that works, great

It works fine now, thanks a lot for your patience 

> hen test if you actually need `https://www.google.com`

I don't, it works fine without `https://www.google.com`

**Comment by Thorin-Oakenpants** [comment] 2022-02-03 12:59
wait, don't go - well, the cookie wasn't session only and we're not sanitizing so it was never removed - I wonder if the YT exception is needed

anyway, I won't get you to test anymore, since I'll probably just make things more confusing

**Comment by CGYoung1040** [comment] 2022-02-03 13:06
> I wonder if the YT exception is needed

I just tried, the YouTube exception is not needed either

> anyway, I won't get you to test anymore, since I'll probably just make things more confusing

Since you helped me out, the least I can do is return the favor and run a few more tests. But as you've seen earlier I'm not sure how helpful I'll actually be

**Comment by Thorin-Oakenpants** [comment] 2022-02-03 14:41
OK, lets try

In a new profile
- add arkenfox user.js and restart: so we have zero cookies and site data
- add `https://accounts.google.com` to site exceptions, nothing else
- then go to YT and login
- close firefox (so session cookies are cleared), open firefox, are you logged in?

If you are logged in, then it shows we only need to SSO site

If you are not logged in, close the browser (so the session cookies are cleared) and reopen
The add `https://www.youtube.com` to site exceptions, go to YT and login. Close, open - are you logged in?

If you are logged in then it shows we don't need `https://www.google.com`

At the end of the day, it doesn't really matter if you keep the YT cookie, since you;re logging n and it probably has site settings in it

**Comment by Thorin-Oakenpants** [comment] 2022-02-04 16:43
OK, I'm done here. I added an example to the wiki page, and I tweaked the 2702 info thanks @rusty-snake

**Closed by Thorin-Oakenpants** 2022-02-04 16:43 UTC
Labels: answered
