### ISSUE TITLE
OCSP partitioning test site?

### ISSUE THREAD

**Issue by Jee-Hex** [arkenfox/user.js#1351] opened 2022-01-26 16:13 UTC
So I was testing out ETP Strict before migrating from FPI to dFPI, and something in `about:networking#dns` caught me off guard. For example, the isolation keys for `github.com` inside a container were `github.com^userContextId=1&firstPartyDomain=%28https%2Cgithub.com%29&partitionKey=%28https%2Cgithub.com%29` and `ocsp.digicert.com^firstPartyDomain=%28https%2Cgithub.com%29` when both `privacy.firstparty.isolate` and `privacy.partition.network_state` were `true`. When I disable FPI and switch to ETP Strict, only `github.com^userContextId=1&partitionKey=%28https%2Cgithub.com%29` was shown but nothing for the OCSP cache (i.e. no `ocsp.digicert.com^partitionKey=%28https%2Cgithub.com%29`).

On the other hand, the isolation keys for Google Safebrowsing and its OCSP were always 
`safebrowsing.googleapis.com^firstPartyDomain=safebrowsing.[blah-blah-blah].mozilla` and `ocsp.pki.goog^firstPartyDomain=safebrowsing.[blah-blah-blah].mozilla`, regardless of whether FPI or dFPI is active.

So I am not sure if this is just a `about:networking` thing and the OCSP cache is actually still being partitioned? Unlike cookies this does not seem to be easily verifiable on the client side.

**Comment by Thorin-Oakenpants** [comment] 2022-01-27 10:15
Hah, funny you should bring up Safe Browsing, as I recently did a series of tests to prove to the fish that SBv4 does not use cookies, and I noticed the syntax used in the logger. I also noticed the same with SB HSTS in a series of tests done for a different reason

Digging way back in bugzilla, there was a discussion about how to name the isolation of the SB cookie jar. Considering it's principal, I'm not surprised that this hasn't been touched by dFPI and continues to have a FPI syntax to ensure isolation from the rest of the browsing process

[privacytests](https://privacytests.org/) doesn't have a full set of state partitioning tests yet (OCSP is not included for starters), and ~~the fish and~~ I have already found 1 false negative and 1 false positive in the state partitioning tests. I'm not sure how to test OCSP without checking it out a bit more, but my gut instinct is to trust what the devs say, and they should have tests in the patches - we should look there for starters

**Comment by fxbrit** [comment] 2022-01-27 12:14
>  they should have tests in the patches - we should look there for starters

https://searchfox.org/mozilla-central/source/security/manager/ssl/tests/unit/test_ocsp_caching.js#407
https://searchfox.org/mozilla-central/source/security/manager/ssl/tests/gtest/OCSPCacheTest.cpp#308

**Comment by Thorin-Oakenpants** [comment] 2022-01-27 15:03
> and ~the fish and~ I have already found 1 false negative and 1 false positive in the state partitioning tests

and two others that aren't robust enough .. someone should pay me for this shit :)

**Comment by Thorin-Oakenpants** [comment] 2022-01-27 16:33
I haven't had time to read _anything_ but I would use a new profile and make sure CRLite is not used (so not nightly) - am concerned _a little_ that your STR include turning off FPI :)

**Comment by vittring** [comment] 2022-01-30 04:32
> am concerned _a little_ that your STR include turning off FPI :)
I am greatly concerned. Either user.js isn't recently updated _or_ it has an override that shouldn't be.

**Comment by KOLANICH** [comment] 2022-01-30 07:06
BTW, has anyone noticed getting SEC_ERROR_OCSP_SERVER_ERROR a lot of times a day?

**Comment by Thorin-Oakenpants** [comment] 2022-01-30 07:07
nope, it's just you bro, they're onto you :)

**Comment by Jee-Hex** [comment] 2022-01-30 15:31
> Either user.js isn't recently updated or it has an override that shouldn't be.

Nope. Just re-tested this on a vanilla 96.0.2 portable profile and still got the same results. The only prefs I flipped were:

```javascript
user_pref("security.OCSP.require", true);
user_pref("app.normandy.enabled", false);
user_pref("privacy.partition.network_state", false);
user_pref("security.remote_settings.crlite_filters.enabled", false);
user_pref("security.pki.crlite_mode", 0);
user_pref("security.remote_settings.intermediates.enabled", false);
```

Maybe my test is flawed? Mozilla's [tests](https://hg.mozilla.org/mozilla-central/rev/28fc69e4c7c6) only seem to care about what happens when the pref is on.

**Comment by Thorin-Oakenpants** [comment] 2022-01-30 15:34
I don't understand .. why are you turning off `privacy.partition.network_state` - that's what partitions this stuff

**Comment by vittring** [comment] 2022-01-30 20:38
Why are you messing with [CRLite ](https://blog.mozilla.org/security/2020/01/21/crlite-part-3-speeding-up-secure-browsing/)now? and that mode is more efficient by design, I thought? Did I miss something here?

**Comment by Thorin-Oakenpants** [comment] 2022-03-10 00:34
I'm not in a position to check this. We'll have to rely on Mozilla's own internal tests and external tests like privacytests.org when/if Arthur adds it

**Comment by Thorin-Oakenpants** [comment] 2022-06-19 00:04
closing ... this will never be done (testing from our/my side) .. I appreciate testing upstream code, and bugz happen, but this is just beyond my time and scope

**Closed by Thorin-Oakenpants** 2022-06-19 00:04 UTC
