### ISSUE TITLE
Loaded images seem to quickly disappear

### ISSUE THREAD

**Issue by firefoxlover** [arkenfox/user.js#1768] opened 2023-11-21 20:35 UTC
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

🟪 REQUIRED INFO
  - Browser version & OS: firefox RPM 118.0.1 Fedora
  - Steps to Reproduce (STR):

[Load this website on Wikimedia searching for "tux" images](https://commons.wikimedia.org/w/index.php?search=tux&title=Special:MediaSearch&go=Go&type=image)

Scroll down a bit and scroll up again, or just do nothing and wait.

  - Expected result: images load after another and stay there
  - Actual result: images load and then disappear again quickly?

  - Console errors and warnings: dont know
  - Anything else you deem worth mentioning: tested this on default firefox

[arkenfox-image-caching-error.webm](https://github.com/arkenfox/user.js/assets/78762110/13bb3a0d-ac00-4b8c-a649-a6e8c28c1521)

**Comment by Thorin-Oakenpants** [comment] 2023-11-22 05:18
FWIW - can't replicate on windows

**Comment by Thorin-Oakenpants** [comment] 2023-11-24 14:01
@firefoxlover

step 1: does this happen on Firefox without arkenfox?

step 2:  does this happen once you update to FF120?

Assuming 1 is a no, and 2 is a yes - do you happen to know (i.e you have been using arkenfox for a while) if this only recently started happening, or is it something you only just noticed

**Comment by firefoxlover** [comment] 2023-11-24 19:07
uhm I use Fedora Firefox so I cant just update.

I tested this on a vanilla profile and it didnt happen there.

**Comment by Thorin-Oakenpants** [comment] 2023-11-25 06:08
thanks - I will see what I can test from my end (not linux savy, but I can set up some VMs - atm I only have debian)

my first thought was this might be something to do with wayland changes, so "good" to know it's something in AF and something still happening. I'll have to try and replicate and then [bisect the prefs](https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting#-manual) - that is new profile, add half the user.js ... repeat & rinse

**Comment by firefoxlover** [comment] 2023-12-15 01:32
Some interesting addition: when using Javascript to load all the images, this does not happen. Only on Pages like Duckduckgo when I think the images are loaded through HTML

**Comment by Thorin-Oakenpants** [comment] 2023-12-23 10:37
Update: couldn't replicate the issue in debian 12 (gnome) using FF121

what I did - https://archive.mozilla.org/pub/firefox/releases/121.0/linux-x86_64/en-US/ - I unpacked the bz2 to a folder called FF121 in my downloads, opened it (i.e `Home/Downloads/FF121/firefox`), went to about:support for my profile (which was anew one which doesn't interfere with the debian provided ESR), and copied the AF user.js in. Closed it. Opened it. Check about:config - parrot and all.

**Comment by anhkhoakz** [comment] 2023-12-31 10:36
Are you employing uBlock Origin with Hard or Medium Blocking Mode? If so, ensure that you permit connections necessary for streaming the video or displaying the image.

**Comment by atomGit** [comment] 2024-01-03 06:19
i'm loading the site with uBO strict, with/without JS, ff v121, and cannot reproduce 

i'm not running vanilla arkenfox however - might be useful if OP posted their overrides

**Comment by bkmo** [comment] 2024-01-16 17:46
Cannot reproduce on Arch Linux. Firefox 121, Ubo basically medium mode, arkenfox with some overrides. Basically RFP disabled. Webgl enabled.

**Comment by wrathgewp** [comment] 2024-01-17 15:59
I cannot reproduce it on Fedora 39. I'm using Firefox RPM 121.0.1 with uBlock Origin ( with every 3rd-party filters enabled, as well as ublock's one ), Dark Reader and Bitwarden extensions. The images never disappear

**Comment by rusty-snake** [comment] 2024-01-26 18:34
FWIW: FF118 enabled `image-lazy-loading`.

**Comment by Thorin-Oakenpants** [comment] 2024-02-04 19:51
closing since no-one else has managed to replicate and op seems to have disappeared for now

**Closed by Thorin-Oakenpants** 2024-02-04 19:51 UTC
