### ISSUE TITLE
Strange issue Firefox switching to active window - Window movements?

### ISSUE THREAD

**Issue by jkuj6** [arkenfox/user.js#1158] opened 2021-04-04 13:29 UTC
Ive been having a very strange and annoying issue, it never used to happen before but only noticed it recently.

Basically, if you go to a site like Github, and as soon as you click sign-up, and while thats loading, you switch to another window, like Thunderbird, or your file browser, you will notice that as soon as Github finishes loading the captcha in the backgrounded window, it will switch to Firefox automatically as the active window.
Ive noticed only some sites do this, another of which is a banking site while logging-in half way, i noticed as i was switching between keepass and before i even double clicked the password, it switched me back to firefox active window.

This however, does not happen if you explicitly minimize the firefox window after refreshing the Github sign-up page.

I have successfully reproduced the issue on a VM and it does the same thing. See the GIF video below.
![2021-03-22](https://user-images.githubusercontent.com/59932002/113510202-fd589100-9559-11eb-8fce-d1303fae973d.gif)

To reproduce yourself:

- Open 2 windows, one of them firefox and the other a file-browser or whatever.
- Go to firefox and as soon as you click on the sign-up page, switch to your file-browser window and wait. (DONT minimize firefox, just switch windows)

Tested on Fresh Firefox profile and no user.js settings. Does anyone know whats causing this and what option we could disable on user.js to stop this from happening?

**Comment by Thorin-Oakenpants** [comment] 2021-04-04 14:38
duplicate of `https://github.com/pyllyukko/user.js/issues/510`

Are you using the arkenfox user.js?

**Closed by Thorin-Oakenpants** 2021-04-04 14:38 UTC
