### ISSUE TITLE
Can't see presentation in Google Meet.

### ISSUE THREAD

**Issue by DarknessKiller123** [arkenfox/user.js#1271] opened 2021-11-08 16:00 UTC
I have already enabled WebRTC  and I followed the recipes in the wiki, but I only have audio in Meet, and I can't see the presentation of other people.

**Comment by rusty-snake** [comment] 2021-11-08 16:32
Is there any error in the console?

**Comment by DarknessKiller123** [comment] 2021-11-08 17:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

**Comment by Thorin-Oakenpants** [comment] 2021-11-09 00:19
here's what I could quickly find

### webrtc.peerconnection.datachannel_created - Unknown scalar

- [bugzilla 1584944](https://bugzilla.mozilla.org/show_bug.cgi?id=1584944) - which indicates a password manager issue
- [stackoverflow 54619817](https://stackoverflow.com/questions/54619817/) - which indicates a password manager but is about chrome
  - same with [54181734](https://stackoverflow.com/questions/54181734/)

Are you using a password manager extension?

---

### Unchecked lastError value: Error: Could not establish connection

Then I found
- [bugzilla 1719312](https://bugzilla.mozilla.org/show_bug.cgi?id=1719312) - which mentions about bitwarden (and another extension, so probably any extension could have this issue depending on what it is trying to do)
  - it was closed as a dupe of [bugzilla 1718520](https://bugzilla.mozilla.org/show_bug.cgi?id=1718520)
     - 1718520 seems to think setting `security.tls.enable_0rtt_data` to `false` might help - but that's what arkenfox already sets it to
     - and it was resolved fixed for FF94

What version of Firefox are you using?
Have you tried with all your extensions disabled? What extensions do you have?

**Comment by DarknessKiller123** [comment] 2021-11-09 00:26
I use Troubleshoot mode already, and it isn't working. My password manager was Bitwarden. I had a profile backup and in a profile with all my extensions and without user.js all is working fine. It's weird, because all was working before update.

**Comment by Thorin-Oakenpants** [comment] 2021-11-09 00:34
So, create a new profile, open FF with it to populate it. Close FF. Add arkenfox user.js , add overrides to end of user.js as below, open FF, open about:config and check the parrot pref value, test

and you are on FF94+, right?

```js
/* override recipe: i want to use MEET godamnit ***/

user_pref("_user.js.parrot", "adding DARKNESS overrides");

user_pref("media.peerconnection.enabled", true); // 2001
user_pref("media.peerconnection.ice.no_host", false); // 2001 [may be required]
   // user_pref("media.autoplay.blocking_policy", 0); // 2031 optional [otherwise add site exceptions]
   // user_pref("webgl.disabled", false); // 4520 [required for Zoom]

   // user_pref("media.getusermedia.screensharing.enabled", true); // reset this: removed from user.js v91
   // user_pref("javascript.options.wasm", true); // 5506 reset this: default-inactive in user.js v91
   // user_pref("dom.webaudio.enabled", true); // 8001 reset this: default-inactive in user.js v90

user_pref("_user.js.parrot", "fuckyeah DARKNESS overrides WORKED");

```

**Comment by Thorin-Oakenpants** [comment] 2021-11-10 20:16
@DarknessKiller123 any luck, more info?

**Comment by DarknessKiller123** [comment] 2021-11-10 20:22
I need Google Meet, so I delete the user.js temporaily, but is weird, before it was working and I used it. Is anyway to obtain logs from Firefox?

**Comment by rusty-snake** [comment] 2021-11-10 20:24
If you just delete the `user.js` file but not clean-up `prefs.js` (and site permissions, ...) all changed prefs are still changed (=used).

**Comment by Thorin-Oakenpants** [comment] 2021-11-10 20:28
open `about:support`, scroll down to `Important Modified Preferences`, copy paste the contents, it pastes nice and clean

then rusty can go thru it for you 😁

**Comment by Thorin-Oakenpants** [comment] 2021-11-14 01:11
reopen if you can't work it

**Closed by Thorin-Oakenpants** 2021-11-14 01:11 UTC
