### ISSUE TITLE
PiP - pop out a video, resize, pause, start, pop back in - glitches [not arkenfox: 1810165]

### ISSUE THREAD

**Issue by peternrdstrm** [arkenfox/user.js#1611] opened 2023-01-04 11:10 UTC
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [*] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: Firefox v108.1, Windows 11 22H2
  - Steps to Reproduce (STR): 
  1. Open any website with a video on it (youtube)
  2. Pop picture in picture out
  3. Mess with it for a bit, resize, stop start
  4. Pop it back on
  5. Firefox should be glitched out now
  - Expected result: It just pops back on and that's it
  - Actual result: Firefox glitches out graphically until a restart
  - Console errors and warnings: Haven't seen any
  - Anything else you deem worth mentioning: I've had this issue for a while, but tought that LibreWolf was the reason. I switched back to FF with arkenfox and I still encounter this issue. My overrides do not touch PiP or video playback

---

**Comment by Thorin-Oakenpants** [comment] 2023-01-04 23:49
can't reproduce

**Comment by Thorin-Oakenpants** [comment] 2023-01-05 16:34
What do mean "Firefox glitches" - do you mean Firefox itself, or the video? Have you tried any troubleshooting as per the wiki (maybe it's RFP's timing mitigations)?

**Comment by Thorin-Oakenpants** [comment] 2023-01-06 17:59
^ bump

> Have you tried any troubleshooting as per the wiki 

I see these as well - https://github.com/peternrdstrm/Arkenfox-Overrides/blob/main/user-overrides.js#L12-L15 - did you also change those in LW?

**Comment by peternrdstrm** [comment] 2023-01-11 19:03
> ^ bump
> 
> > Have you tried any troubleshooting as per the wiki
> 
> I see these as well - https://github.com/peternrdstrm/Arkenfox-Overrides/blob/main/user-overrides.js#L12-L15 - did you also change those in LW?

yes, i run these in most of my installs, including both "glitched" ones

**Comment by peternrdstrm** [comment] 2023-01-11 19:04
> What do mean "Firefox glitches" - do you mean Firefox itself, or the video? Have you tried any troubleshooting as per the wiki (maybe it's RFP's timing mitigations)?

I'll send a video showcasing it

**Comment by Thorin-Oakenpants** [comment] 2023-01-11 19:35
> yes, i run these in most of my installs, including both "glitched" ones

Then reset them and see if the problem goes away?

**Comment by peternrdstrm** [comment] 2023-01-12 19:30
this is what I'm talking about, happens consistently
https://user-images.githubusercontent.com/68877792/212162835-2a32ccea-453b-4c02-8c48-5011f7eb591d.mp4

**Comment by peternrdstrm** [comment] 2023-01-12 19:34
I did a little testing. Non-arkenfox firefox seems to also glitch out doing the same thing, just a lot less crazily. My computer has to be the issue, but I can't figure out why. I'll need to test if the bug presists in a VM

**Comment by theltalpha** [comment] 2023-01-13 05:50
Hallo! Please try to find out which pref is causing this issue with the method described here: https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting#-manual

**Comment by Thorin-Oakenpants** [comment] 2023-01-13 07:18
> this is what I'm talking about, happens consistently https://user-images.githubusercontent.com/68877792/212162835-2a32ccea-453b-4c02-8c48-5011f7eb591d.mp4

Wow. I would re-create that with a vanilla Firefox (no arkenfox) and file a Bugzilla. If you can't file a bug, then I can do it for you

> Edit: issue isn't present in a VM on vanilla firefox, arkenfox does glitch out tho

Let's not confuse things. I don;t know if you mean arkenfox master with no overrides, or with your overrides (which seem to make it worse but I doubt is the cause, these are symptoms of a bigger underlying bug IMO).

**Comment by crssi** [comment] 2023-01-13 09:20
I would suspect that this has something to do with graphics adapter and/or graphics drivers and arken has nothing to do with.
VM actually does have different graphics adapter than host.

I have here Nvidia RTX2060 with latest drivers and OS is Win11 and cannot reproduce.
Also I have tried the same on RTX3060.

Which graphics adapter do you have exactly?

**Comment by peternrdstrm** [comment] 2023-01-13 09:25
> I would suspect that this has something to do with graphics adapter and/or graphics drivers and arken has nothing to do with. VM actually does have different graphics adapter than host.
> 
> I have here Nvidia RTX2060 with latest drivers and OS is Win11 and cannot reproduce. Also I have tried the same on RTX3060.
> 
> Which graphics adapter do you have exactly?

I have an ancient AMD R5 200 series "card" (still runs games) and did work before version 107 I think.

**Comment by Thorin-Oakenpants** [comment] 2023-01-13 09:44
You could go to about:support and copy the graphics section and paste it here (or more appropriately in a bugzilla) - at least that is a start - it is odd though that it's only with PiP steps to trigger it (IIUIC)

You said you've "had this issue for a while", but not always. Do you know when it started? I suspect there will be some graphics related/web-render-related pref flip/change and your graphics card is an edge case?

**Comment by crssi** [comment] 2023-01-13 09:45
Would you be so kind and try to reproduce on some newer GPU?
I haven't look into FF changes between those versions, but they might "modernize" GPU utilization or simply introduced a bug affecting old GPUs.

**Comment by Thorin-Oakenpants** [comment] 2023-01-13 09:49
> and did work before version 107 I think

I should learn to read before posting

You can test this by downloading a portable version and testing it - then delete it
- https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./
- easy as pie
   - download 107, run the installer, unpack to e.g. c://temp/FF107, test, note result
   - download 106, ^ ditto but use c://temp/FF106
   - delete portables after diagnosis

You could even use moz-regression to find the actual bug, but I don't expect you to do that

**Comment by peternrdstrm** [comment] 2023-01-13 15:09
> You could go to about:support and copy the graphics section and paste it here (or more appropriately in a bugzilla) - at least that is a start - it is odd though that it's only with PiP steps to trigger it (IIUIC)
> 
> You said you've "had this issue for a while", but not always. Do you know when it started? I suspect there will be some graphics related/web-render-related pref flip/change and your graphics card is an edge case?

incase that my gpu is the cause, would disabling hardware acceleration fix the issue?

**Comment by peternrdstrm** [comment] 2023-01-13 15:12
> > and did work before version 107 I think
> 
> I should learn to read before posting
> 
> You can test this by downloading a portable version and testing it - then delete it
> 
> * https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./
> * easy as pie
>   
>   * download 107, run the installer, unpack to e.g. c://temp/FF107, test, note result
>   * download 106, ^ ditto but use c://temp/FF106
>   * delete portables after diagnosis
> 
> You could even use moz-regression to find the actual bug, but I don't expect you to do that

both 107 and 106 are affected, I'll try a few other ones, possibly ESR

**Comment by peternrdstrm** [comment] 2023-01-13 15:16
ESR seems to work just fine, I need to test it with arkenfox

**Comment by theltalpha** [comment] 2023-01-14 06:28
What about the "normal" version 102 of Firefox? If this is also working fine, then we would know the error has been introduced between versions 103 and 106 and it would be easy for you to find out the actual version where the error has been introduced.

**Comment by peternrdstrm** [comment] 2023-01-14 19:43
> What about the "normal" version 102 of Firefox? If this is also working fine, then we would know the error has been introduced between versions 103 and 106 and it would be easy for you to find out the actual version where the error has been introduced.

After some testing, I can confirm that 102 works perfectly

**Comment by theltalpha** [comment] 2023-01-15 05:53
So you continue testing version 103 to 106 to see where the error first appeared?

**Comment by peternrdstrm** [comment] 2023-01-15 17:03
I tested as low as 105, and that has the issue, so I'm checking 104 right now, I'll update this comment with my findings

**Comment by theltalpha** [comment] 2023-01-16 06:25
For traceability reasons, maybe you want to post the link to the Bugzilla report you made here?

**Comment by peternrdstrm** [comment] 2023-01-16 07:12
> For traceability reasons, maybe you want to post the link to the Bugzilla report you made here?

https://bugzilla.mozilla.org/show_bug.cgi?id=1810165
Here

**Comment by theltalpha** [comment] 2023-01-17 05:21
I think you should add to the Bugzilla entry the information that the bug was apparently introduced with version 105.

**Comment by Thorin-Oakenpants** [comment] 2023-01-17 06:42
> I have made a bugzilla report but that hasn't been noticed

When you want action on something, you need to give the devs something to work with. If you used moz-regression you could find the actual bug that regressed it. You'd want to bisect the dates when 105 was in nightly

Other than that, at least your graphics about:support information would be nice for them

**Comment by Thorin-Oakenpants** [comment] 2023-01-17 06:43
https://mozilla.github.io/mozregression/install.html

**Comment by Thorin-Oakenpants** [comment] 2023-01-17 07:01
I won't mark it as invalid (which is what I do to non AF issues) for when you link to here, but honestly, you should just put all the info into the bugzilla and not mention here at all, it is a distraction to them

closing

**Closed by Thorin-Oakenpants** 2023-01-17 07:01 UTC
Labels: firefox bug

**Comment by peternrdstrm** [comment] 2023-01-17 19:02
> I won't mark it as invalid (which is what I do to non AF issues) for when you link to here, but honestly, you should just put all the info into the bugzilla and not mention here at all, it is a distraction to them
> 
> closing

Thank you for the assistance either way!
