### ISSUE TITLE
tracking: migrate cookie lifetime and sanitize cookie/offlineApps

### ISSUE THREAD

**Issue by aleyvo** [arkenfox/user.js#1441] opened 2022-05-03 17:58 UTC
Just a follow-up to the "keep cookie + site data exceptions on close" functionality (issues #1256 and #1291.)

Considering that:

- `privacy.sanitize.sanitizeOnShutdown` is not "All or Nothing" anymore, i.e. `privacy.clearOnShutdown.cookies` and `privacy.clearOnShutdown.offlineApps` now respect website exceptions as of FF99 ([1681701](https://bugzilla.mozilla.org/show_bug.cgi?id=1681701), [code](https://hg.mozilla.org/mozilla-central/rev/0ebcf4b57240));

- `network.cookie.lifetimePolicy` is soon/not so soon to be deprecated ([1681493](https://bugzilla.mozilla.org/show_bug.cgi?id=1681493), [1764761](https://bugzilla.mozilla.org/show_bug.cgi?id=1764761)).

Would it be the right time to update section 2800, deprecating `network.cookie.lifetimePolicy` and setting both `privacy.clearOnShutdown.cookies` and `privacy.clearOnShutdown.offlineApps` to **true**? Functionality wise, thing _should_ continue to be the same. It would be more of a future-proof measure.

**Comment by Thorin-Oakenpants** [comment] 2022-05-03 18:41
The only issue I have is timing
- there is a migration planned
   - i.e if users have lifetime policy = 2, then enable sanitize on close and check cookies and offlineApps - and some logic to uncheck the other options IF sanitize on close was disabled
   - IDK what happens if the prefs are `modified` - e.g. us
   - and for subsequent starts the user.js will reset them

In other words I _**want**_ to avoid the migration code getting triggered. So as long as we can switch at least one release before the pref is deprecated, then that's what I want to do

My best guess is that they will want to get this done in ESR102 at the latest. For now it is **_not in FF101_** and we can safely keep using the current setup.

I would rather not pull the trigger on changing until I know it's production ready. There's a bit to digest, and I would want to know it's all working as intended. For example, 101 introduced some sanitizing speed perfs, which caused a regression with containers and subdomains (which was fixed). What I'm saying is I want to let the bugs manifest if there are any. And there is still code to be changed where lifetime policy is used.

We can afford to wait. The only benefit I see is that it would then allow service workers, but since we've lived without those for the last four years, I don't think another release or two matters

We can keep this issue open as the ToDo and for tracking (although I am already tracking it)

**Comment by Thorin-Oakenpants** [comment] 2022-05-05 15:49
Case 2 - We are going to be making clearOnShutdown true for both `cookies` (cookies) and `offlineApps` (idb, service worker cache, local storage, quota manager stuff). IDK if that changes the google dark theme being remembered, it depends on where it is stored and it's OA (origin attributes)

Anyway, when ready, we need to test this without using dFPI exceptions .. because, well fuck .... have a read
- `https://github.com/privacyguides/privacyguides.org/discussions/941#discussioncomment-2674048` along with subsequent/previous comments

Anyway, personally, I have uBO in with no 3rd party by default, and I only have five site-data exceptions, and only one of those sites can be used as a SSO, so ... [The Almighty knows I am out of this mess, but he's pretty sure you're fucked](https://www.imdb.com/title/tt0112573/characters/nm0641244) :)

**Comment by rn83** [comment] 2022-05-05 19:10
I do have `offlineApps` checked. The logic is that when allowing `https://accounts.google.com`, a cookie of domain `.google.com` (as shown by devtools > storage) will not be cleared if not session-only, regardless of the subdomain by which it was added. If I modify a cookie's domain to `www.google.com`, it will be cleared on shutdown. (BTW, by doing this to cookie name `NID` resets the dark theme setting of `www.google.com`)

**Comment by Thorin-Oakenpants** [comment] 2022-05-05 20:21
this stuff can get confusing fast, and tests need to also check subdomains and probably scheme. AFAIK shit should be eTLD+1 (and i think scheme)

**Comment by Thorin-Oakenpants** [comment] 2022-05-05 20:23
this stuff probably intersects with #1293 and the longer I can ignore it all, the better TBH

**Comment by aleyvo** [comment] 2022-05-05 21:26
> Anyway, when ready, we need to test this without using dFPI exceptions .. because, well fuck .... have a read
> 
>     * `https://github.com/privacyguides/privacyguides.org/discussions/941#discussioncomment-2674048` along with subsequent/previous comments

Wait... So website exceptions don't even know that cookie partitions are a thing? I feel like I've been carefully feeding the monkey with small amounts of cookies each day, only to know that it had access to my whole jar of cookies since the beginning.

Have a bunch of site exceptions. Seems like you're right, Mr. Stephen. I'm sure to be f*cked.

**Comment by Thorin-Oakenpants** [comment] 2022-05-06 06:40
right .. here we go .. patchs underway bitches, early in the 102 nightly cycle
- https://bugzilla.mozilla.org/show_bug.cgi?id=1681495#c7 - Switch clear cookies and site data checkbox to control sanitization prefs
- https://bugzilla.mozilla.org/show_bug.cgi?id=1681498#c7 - Migrate users from network.cookie.lifetimePolicy to sanitize on shutdown prefs

**Comment by Thorin-Oakenpants** [comment] 2022-05-06 06:41
The UI settings changing is important as well for the user.js

**Comment by rn83** [comment] 2022-05-06 08:04
> patchs underway

When `network.cookie.lifetimePolicy = 2`, cookies are handled in a two-phase manner.
- Pahse 1: All cookies, unless permanently allowed, are marked as session-only when added.
- Phase 2: On shutdown, cookies that are session-only or not in the exception list are purged.

If migrated to `privacy.sanitize.sanitizeOnShutdown`, there won't be a phase 1 (as of Firefox 100) and thus the situation above. Will this be covered in the future?

**Comment by Thorin-Oakenpants** [comment] 2022-05-07 15:05
I can't follow that.

If you migrate from lifetime = 2 then "phase" 1 won't happen (unless permanently set as `Allow for session`) because the default behavior changed.

And thus, "phase 2" also won't happen, because you aren't setting cookies to be session only. Except, session cookies (such as bank ones etc) have always been cleared on close, that's what the "session" part means, so in technically, phase 2 has always happened

---

This is a two stepper, don't think too hard about it
- lifetime pref changed to default / deprecated: all cookies are now kept by default: does not affect your existing `Allow` cookies
- 2x sanitize on close prefs: _as long as both prefs_ respect the site exception, then we're good
   - side note: this actually reduces some sanitizing as before I could keep the "cookie + site data" exceptions but bulk-clear all "site data"

101 is basically done and dusted, and looks like 102 will "migrate" existing users, so at this point we have almost two months to work it out

**Comment by Thorin-Oakenpants** [comment] 2022-05-12 05:37
just a note to myself, on how to frame this in the user.js. `privacy.sanitize.sanitizeOnShutdown` is still "All or Nothing", except cookies + site data - which will now have two UIs (personally I think they should just move the two checkboxes out of "history" - maybe they can clean that up at a later date)


rough as F draft
```js
/* SANITIZE ON SHUTDOWN
/* 2801: enable Firefox to clear items on shutdown
 * [NOTE] If using the second setting below, this
 * [SETTING] Privacy & Security>History>Custom Settings>Clear history when Firefox closes
 * [SETTING] Privacy & Security>Cookies and Site Data>Delete cookies and site data when Firefox is closed ***/
user_pref("privacy.sanitize.sanitizeOnShutdown", true);

/** COOKIES + SITE DATA : ALLOWS EXCEPTIONS ***/
/* 2810: delete cookies and site data on exit
 * FF102+, when enabled this also enabled 2801
 * [NOTE] A "cookie" block permission also controls localStorage/sessionStorage, indexedDB,
 * sharedWorkers and serviceWorkers. serviceWorkers require an "Allow" permission
 * [NOTE] "offlineApps": Offline Website Data: localStorage, service worker cache, QuotaManager (IndexedDB, asm-cache)
 * [SETTING] Privacy & Security>Cookies and Site Data>Delete cookies and site data when Firefox is closed
 * [SETTING] to add site exceptions: Ctrl+I>Permissions>Cookies>Allow
 * [SETTING] to manage site exceptions: Options>Privacy & Security>Permissions>Settings ***/
user_pref("privacy.clearOnShutdown.offlineApps", true); // [DEFAULT: false]
user_pref("privacy.clearOnShutdown.cookies", true);  // [DEFAULT: true]


/** THE REST: ALL OR NOTHING ***/
/* 2820: set/enforce what items to clear on shutdown (if 2810 is true) [SETUP-CHROME]
 * These items do not use exceptions, it is all or nothing (1681701)
 * [NOTE] If "history" is true, downloads will also be cleared
 * [NOTE] "sessions": Active Logins: refers to HTTP Basic Authentication [1], not logins via cookies
 * [SETTING] Privacy & Security>History>Custom Settings>Clear history when Firefox closes>Settings
 * [1] https://en.wikipedia.org/wiki/Basic_access_authentication ***/
user_pref("privacy.clearOnShutdown.cache", true);     // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.downloads", true); // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.formdata", true);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.history", true);   // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.sessions", true);  // [DEFAULT: true]
   // user_pref("privacy.clearOnShutdown.siteSettings", false); // [DEFAULT: false]

```

and at this point I'm really concerned, because as I'm trying to word the notes/description in 0801, I realized that all the defaults for cache, downloads, formdata, history are true, and the code I think is going to change those to false (so users don't get their shit wiped when only asking to remove cookies and site data) - but I think it also respects the current settings if 0801 is enabled - which makes no sense except in the migration, because that's what the UI will now toggle

and we need to fit the cpd ones in - we will need to test that the cookie + offlineApps respect exceptions

this is not going to be all that easy to frame, and we can't do anything until we can test the final product

**Comment by aleyvo** [comment] 2022-05-13 18:16
> and at this point I'm really concerned, because as I'm trying to word the notes/description in 0801, I realized that all the defaults for cache, downloads, formdata, history are true, and the code I think is going to change those to false (so users don't get their shit wiped when only asking to remove cookies and site data) - but I think it also respects the current settings if 0801 is enabled - which makes no sense except in the migration, because that's what the UI will now toggle

### Migration Code
The migration code will only do its thing if `network.cookie.lifetimePolicy` is `2`. **If this is the case, then 2801 will be enabled and `*.cookies`, `*.offlineApps`, and `*.cache` will be set to true and `network.cookie.lifetimePolicy` will be wiped. But before enabling 2801, the code will check if it has already been enabled - if it has NOT, then `*.history`, `*.downloads`, `*.formdata`, `*.sessions`, and `*.siteSettings` will be set to false to avoid unintentional wiping of user data when flipping 2801**.

If lifetimePolicy is not `2`, then the migration won't be triggered. If we were to deprecate this lifetimePolicy pref in arkenfox's user.js, and then to run prefsCleaner, it seems like we could avoid this migration altogether.

The migration code can be seen [here](https://hg.mozilla.org/integration/autoland/rev/190c8814b474#l1.12).

### UI Code
The UI code is a little trickier, but here is my understanding of it:

* Scenario 1: If ANY of the prefs 2801, `*.cookies`, `*.offlineApps`, OR `*.cache` is set to false in prefs.js, then "Delete cookies and site data when Firefox is closed" will be shown as unchecked when _about:preferences_ is loaded. **In this case, whenever the user checks this option, 2801, `*.cookies`, `*.offlineApps`, and `*.cache` will ALL be set to true in prefs.js. But before enabling 2801, the code will check if it has already been enabled - if it has NOT, then `*.history`, `*.downloads`, `*.formdata`, `*.sessions`, and `*.siteSettings` will be set to false to avoid unintentional wiping of user data when flipping 2801**.

* Scenario 2: If prefs 2801, `*.cookies`, `*.offlineApps`, AND `*.cache` are ALL set to true in prefs.js, then "Delete cookies and site data when Firefox is closed" will be shown as checked when _about:preferences_ is loaded. **In this case, whenever the user unchecks this option, `*.cookies`, `*.offlineApps`, and `*.cache` will be set to false in prefs.js. And 2801 will only be set to false if all of the other `clearOnShutdown.*` prefs are also set to false**.

**Whenever the user changes ANY of the prefs 2801, `*.cookies`, `*.offlineApps`, OR `*.cache` in _about:preferences_, if this were to change the status of the "Delete cookies and site data when Firefox is closed" checkbox, then Scenario 1 or Scenario 2 would be reapplied, as if the user was clicking directly at the "Delete cookies and site data when Firefox is closed" checkbox**.

Regarding arkenfox, if we were to set `*.cookies` and `*.offlineApps` to true in user.js, and considering that 2801 and `*.cache` are already set to true, then "Delete cookies and site data when Firefox is closed" would be shown as checked in _about:preferences_. But both scenarios, 1 and 2, would only happen with _explicit_ user interaction. In other words, no flipping of prefs set by arkenfox should happen automatically. So arkenfox should be fine.

The UI code can be seen [here](https://hg.mozilla.org/integration/autoland/rev/c553d7f2e586#l3.183).

**Comment by aleyvo** [comment] 2022-05-13 18:46
> and we need to fit the cpd ones in - we will need to test that the cookie + offlineApps respect exceptions

As of FF 99, `clearOnShutdown.cookies` and `clearOnShutdown.offlineApps` do respect website exceptions, but `cpd.cookies` and `cpd.offlineApps` do not. I believe this behavior will be kept the same when FF 102 comes out, because it would be the only way to clear all website data at once, even from exceptions, if the user wanted to.

But I think arkenfox should keep `cpd.cookies` and `cpd.offlineApps` to false, to preserve user data in an eventual cpd cleaning. After all, if the user really wants to clear cookies and offlineApps exceptions when using cpd, he is just two checkboxes away from that - no pain at all.

**Comment by Thorin-Oakenpants** [comment] 2022-05-13 21:49
i'm not "worried" about the migration code, I'm worried that toggling the UI causes odd behavior, but now I've had a sleep I _think_ the logic might be ok

> because it would be the only way to clear all website data at once, even from exceptions, if the user wanted to

That's what manage site data is for. `cpd` should follow the same logic and those two prefs respect exceptions

**Comment by aleyvo** [comment] 2022-05-14 13:24
You're right, Thorin. I had forgotten about `manage data` + `clear data`. They're really the guaranteed way to clear exceptions, selectively or all at once. My previous reasoning is plain wrong.

But even having it, Mozilla seems to be trying to push `cpd` not to respect exceptions. There's a [unit test](https://hg.mozilla.org/mozilla-central/rev/0ebcf4b57240#l2.77) ensuring this behavior, at least for cookies. Maybe they thought it would be easier for end users? I don't know. Time will tell how this evolves.

**Comment by Thorin-Oakenpants** [comment] 2022-05-14 14:15
That was back in Feb. Lets just see what happens. One other reason this is a bit icky, is that I think the same codebase is used for forget about this site, and if they wanted to have cpd behave the same as clearonshutdown, then they might have to add more engineering so it knows if you are using forget about this site or ctrl-shift-del - and maybe that's not worth it in their eyes

personally, I can see confusion if cpd behavior differs

**Comment by Thorin-Oakenpants** [comment] 2022-06-03 06:55
I hope you all realize that this was pushed back to FF103 at best (they may back port it to ESR at some point, IDK - I hope they do, so everyone is in sync)

**Comment by Thorin-Oakenpants** [comment] 2022-06-19 23:44
fuck, I think the migration is in 102

**Comment by Thorin-Oakenpants** [comment] 2022-06-29 07:52
^ yup: https://old.reddit.com/r/firefox/comments/vn68tr/firefox_is_unchecking_delete_cookies_and_site/

oh well, what a messy UI and consistency until it gets resolved

**Comment by Thorin-Oakenpants** [comment] 2022-06-29 08:53
nits please: draft 1
- pref changes: lifetime->inactive, onshutdown cookies+offlineApps = true
- using FF102+ as the version (don't care if parts of it were hooked up in FF99 or whatever)
- manual sanitizing is already done in https://github.com/arkenfox/user.js/pull/1477/commits/0c3c0ce3d834b38f99172bee84dc011501133c76

```js
/*** [SECTION 2800]: SHUTDOWN & SANITIZING ***/
user_pref("_user.js.parrot", "2800 syntax error: the parrot's bleedin' demised!");
/** COOKIES + SITE DATA: DO NOT USE FF102+ ***/
/* 2801: delete cookies and site data on exit
 * 0=keep until they expire (default), 2=keep until you close Firefox
 * [NOTE] This is now obsolete and replaced by sanitize on shutdown (2810)
 * [SETTING] Privacy & Security>Cookies and Site Data>Delete cookies and site data when Firefox is closed ***/
   // user_pref("network.cookie.lifetimePolicy", 2);
/* 2802: delete cache on exit [FF96+]
 * [NOTE] We already disable disk cache (1001) and clear on exit (2812) which is more robust
 * [1] https://bugzilla.mozilla.org/1671182 ***/
   // user_pref("privacy.clearsitedata.cache.enabled", true);

/** SANITIZE ON SHUTDOWN: ALLOWS COOKIES + SITE DATA EXCEPTIONS FF102+ ***/
/* 2810: enable Firefox to clear items on shutdown (2811)
 * [NOTE] Exceptions: A "cookie" block permission also controls "offlineApps" (2811).
 * serviceWorkers require an "Allow" permission. For cross-domain logins, add exceptions for
 * both sites e.g. https://www.youtube.com (site) + https://accounts.google.com (single sign on)
 * [SETTING] Privacy & Security>History>Custom Settings>Clear history when Firefox closes
 * [SETTING] to add site exceptions: Ctrl+I>Permissions>Cookies>Allow (when on the website in question)
 * [SETTING] to manage site exceptions: Options>Privacy & Security>Permissions>Settings ***/
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
/* 2811: set/enforce what items to clear on shutdown (if 2810 is true) [SETUP-CHROME]
 * [NOTE] If "history" is true, downloads will also be cleared
 * [NOTE] "sessions": Active Logins: refers to HTTP Basic Authentication [1], not logins via cookies
 * [NOTE] "offlineApps": Offline Website Data: localStorage, service worker cache, QuotaManager (IndexedDB, asm-cache)
 * [SETTING] Privacy & Security>History>Custom Settings>Clear history when Firefox closes>Settings
 * [1] https://en.wikipedia.org/wiki/Basic_access_authentication ***/
user_pref("privacy.clearOnShutdown.cache", true);     // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.downloads", true); // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.formdata", true);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.history", true);   // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.sessions", true);  // [DEFAULT: true]
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.cookies", true);
   // user_pref("privacy.clearOnShutdown.siteSettings", false); // [DEFAULT: false]
```

**Closed** 2022-06-29 09:46 UTC
Labels: tracking | watching

**Comment by Thorin-Oakenpants** [comment] 2022-06-29 09:50
https://github.com/arkenfox/user.js/pull/1477/commits/aa7d7c24ea2a88e09de017d4f6bbacd89bac8a05

I also merged the old 2802 pref into 2810's and renumbered 2812+ -> 2820's (and updated wiki reference numbers)

**Comment by Thorin-Oakenpants** [comment] 2022-06-29 12:48
now I'm losing all cookies every few sessions - my user.js is the same as the v102 one in PR

**Comment by aleyvo** [comment] 2022-06-29 13:44
I've been using these changes of arkenfox-102 PR for a week (done by myself, in FF 101), and I have not experienced this issue yet. Maybe it's a bug introduced by FF 102?

**Comment by Thorin-Oakenpants** [comment] 2022-06-29 16:06
IDK why it happened again, or even the first time (can't be assed) - I modified my user.js before updating to 102 (to avoid the migration and am 75% sure I reset the pref (or maybe I decided to let the migration do it for kicks). Anyway, doesn't seem to be happening now.

I did subsequently check the lifetime pref UI in cookies and site data, and then restarted, but I fail to see how that does anything besides trigger another migration .. so `¯\_(ツ)_/¯`

**Comment by Thorin-Oakenpants** [comment] 2022-06-29 19:51
So the "delete cookies and site data" checkbox in 102 still changes the lifetime pref, which then proceeds to uncheck itself and migrate again on next start - this is changed in 103 - https://bugzilla.mozilla.org/show_bug.cgi?id=1681495

The other one is every time you play with that checkbox, it resets to deleting cache - see comments https://old.reddit.com/r/firefox/comments/vn68tr/firefox_is_unchecking_delete_cookies_and_site/

I was going to try and shoehorn a warning not to touch that UI setting, but I ended up moving the pref to deprecated, and it's only 4 more weeks until it's semi-resolved. We should keep an eye on updating the pref info for that checkbox

**Comment by aleyvo** [comment] 2022-06-29 20:18
This weird issue has just happened to me. There was an electrical outage here... when I reopened everything, all my cookies and local storage were gone, just like Thanos. I'm still using FF 101, with arkenfox-102 PR.

**Comment by Thorin-Oakenpants** [comment] 2022-06-29 21:40
^ that's a bug that has been fixed in an upcoming release - I'll report back with the bugzilla for ya

for me it's now all stable as fuck, been testing and opening and closing shit for the last 5 hours

**Comment by Thorin-Oakenpants** [comment] 2022-06-29 21:42
> just like Thanos

stop over-reacting ... Thanos was only half :)

**Comment by Thorin-Oakenpants** [comment] 2022-07-01 07:08
Well, fuck .. there it goes for the third time

**Comment by aleyvo** [comment] 2022-07-01 12:41
Another electrical outage and another Thanos' snapping. I'll stick to FF101 and lifetimePolicy until FF103 comes out. July 26th seems so far away in the future :(

**Comment by aleyvo** [comment] 2022-07-01 13:43
If I kill FF process, it also happens. [1771024](https://bugzilla.mozilla.org/show_bug.cgi?id=1771024) says that FF101 is unaffected, but that's the version I'm using. I don't get it.

**Comment by opusforlife2** [comment] 2022-07-01 18:39
I'd like to confirm once because of the seemingly complicated mess here.

I use AF without overriding any cookie-related prefs at all. Everything has the AF default value. No cookie or site data exceptions either. Will it be fine to update to Firefox 102 with the 102 AF? Or should I stay on 101 and wait until 103 like aleyvo intended to above?

**Comment by Thorin-Oakenpants** [comment] 2022-07-01 23:05
Aleyvo's issue is with unexpected shutdowns, which was always the case with sanitize onShutdown - so he's going to stick with making all cookies session-only (lifetime pref) and not onShutdown those (cookies, offlineApps). You can't do that in 102 (make all cookies session cookies)

AF v102 will out soon. There's no need to wait IMO. It's working (albeit godamn, there's something fishy about losing them all periodically with a graceful shutdown - maybe that's it, sometimes it doesn't record a graceful shutdown, IDK - this is just my anecdata - it should be solid as fuck - it's just the UI is a mess IMO).

**Comment by opusforlife2** [comment] 2022-07-01 23:13
Thanks. Yeah, I don't need to retain any data or fiddle with the UI; I just want that the data that is supposed to be erased, actually is erased.

**Comment by Thorin-Oakenpants** [comment] 2022-07-06 05:23
and .. fuck .. a 4th time
