### ISSUE TITLE
GitLab browser check is not redirecting

### ISSUE THREAD

**Issue by thacoon** [arkenfox/user.js#1259] opened 2021-09-28 15:01 UTC
Before showing the login page, GitLab does a browser check and then redirects the user to the login page. GitLab does a `GET | https://gitlab.com/users/sign_in` request, but it returns `503 Service unavailable`. However, if I disable the `user.js` and use the Firefox default settings the browser check is successful and I get redirected to the GitLab login page.

[Link to GitLab Login](https://gitlab.com/users/sign_in)

Does anyone else experience the same issue?

Additional information:
- I am using `version 92-alpha`
- Firefox 92.0 (64-bit) on Arch Linux
- I have some custom `user-overrides.js` but if I use the default `user.js` the problem persists

**Comment by rusty-snake** [comment] 2021-09-28 15:09
Duplicate of #1253

**Closed** 2021-09-28 19:25 UTC

**Comment by Thorin-Oakenpants** [comment] 2021-09-28 20:16
Duplicate of #1253
