### ISSUE TITLE
Can't get logins to be remembered at all.

### ISSUE THREAD

**Issue by Roseoid** [arkenfox/user.js#1339] opened 2022-01-21 04:30 UTC
I've done the following modifications to my user.js:
```
user_pref("keyword.enabled", true);
user_pref("network.http.referer.XOriginPolicy", 1);
user_pref("privacy.clearOnShutdown.history", false);
user_pref("privacy.clearOnShutdown.sessions", false);
user_pref("privacy.cpd.sessions", false);
user_pref("dom.storage.next_gen", false);
```

I've tried following the other articles, nothing has worked, or I'm just being stupid. I've gotten this stuff to work before, I've just recently moved to another OS.

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 04:43
duplicate of #1311, #1291, #1278, #1223  - add site exceptions

**Closed by Thorin-Oakenpants** 2022-01-21 04:43 UTC

**Comment by Roseoid** [comment] 2022-01-21 04:48
> duplicate of #1311, #1291, #1278, #1223 - add site exceptions

`user_pref("network.cookie.lifetimePolicy", 2);` works. Thank you.

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 04:49
`network.cookie.lifetimePolicy` is NOT a site exception

**Comment by Roseoid** [comment] 2022-02-19 05:33
> `network.cookie.lifetimePolicy` is NOT a site exception 🤦 🤦‍♂️ 🤦‍♀️ :pants_facepalming:

mald

**Comment by Thorin-Oakenpants** [comment] 2022-02-19 06:06
what does mald mean?

anyway, in case you need it ... the wiki got an update
- see THIS bit - https://github.com/arkenfox/user.js/wiki/3.2-Overrides-[Common]#-keep-logins
