### ISSUE TITLE
Console doesn't work [solved: dom.IntersectionObserver.enabled, inactive since v68 - run your prefsCleaner people!!!]

### ISSUE THREAD

**Issue by LtqxWYEG** [arkenfox/user.js#1026] opened 2020-10-01 17:35 UTC
Hi :)

  - browser version
81.0.1 (64-bit)

  - Steps to Reproduce (STR)
I guess just using the user.js?

  - actual result
Both browser and web console aren't working. They show nothing: The console "script" doesn't seem to load.

  - expected result
They should show something.

  - anything else you deem worth mentioning
I tried with a different profile that doesn't use this user.js, and there both consoles work fine.
This was also an issue with versions before the current one. It's like this for quite a while. Just now I am annoyed enough to do something about it. xD

  - Clear all of this when you're ready to type.
No. :P

Thank you

**Comment by Thorin-Oakenpants** [comment] 2020-10-01 18:24
> This was also an issue with versions before the current one. It's like this for quite a while. Just now I am annoyed enough to do something about it.

Have you done a binary troubleshooting? You should be able to get an answer in about 4 or 5 tests (as compared to getting annoyed and waiting five weeks)

**Comment by Thorin-Oakenpants** [comment] 2020-10-01 18:34
FWIW I don't use the console in my main FF - but I have nightly open with the console all the time. I found about five weeks ago (same time frame as you) that the browser console (which I have with `show content messages` enabled) when open would freeze the chrome UI - so I switched to the web console, which I find a pain in the ass, opening, closing, not being open after flipping to new tabs and so on. But I don't run the user.js in Nightly which I only use for testing shit, hence I haven't seen your issue

Here's a gif
![console](https://user-images.githubusercontent.com/16656956/94848941-3c275600-0414-11eb-93a0-938666f62359.gif)

as to the browser console not showing much or anything (I kinda had a quick look in my main FF, so I can confirm) - maybe @earthlng knows - this is more his area .. otherwise since you have indicated it's something in the user.js, do a binary troubleshoot .. otherwise I might get around to this

**Comment by Thorin-Oakenpants** [comment] 2020-10-01 18:38
browser console is pretty much broken for me without the user.js - ctrl-shift-j doesn;t even work on my nightly, and opening it still freezes the chrome. maybe it something to with fission?

web console seems to work though, in my main FF 80 with user.js

**Comment by Thorin-Oakenpants** [comment] 2020-10-01 18:51
Actually, I can't reproduce. My main FF80 which has the user.js pretty much in it's default state - both consoles are working perfectly fine. I think I misunderstood what your problem is

Create a brand new profile, add the user.js only - restart ... does the problem still happen?

**Comment by LtqxWYEG** [comment] 2020-10-01 20:33
I'll try tomorrow.
What do mean with binary troubleshooting?

**Comment by icpantsparti** [comment] 2020-10-01 23:40
Perhaps it is <code>dom.IntersectionObserver.enabled</code>?  Browser and Web Console will show nothing (blank panels) when that is set false.

That pref was set in older arkenfox user.js, upto around version 66, and inactive (commented out) since.

**Comment by Thorin-Oakenpants** [comment] 2020-10-02 05:54
binary (keep halving): test half, based on results test a quarter, based on results test an eight ... [here](https://github.com/arkenfox/user.js/wiki/1.4-Troubleshooting#small_orange_diamond-manual-troubleshooting)

**Comment by Thorin-Oakenpants** [comment] 2020-10-02 06:59
IIRC, `dom.IntersectionObserver.enabled` breaks some functionality in extensions - e.g. the panel in uBO/uM ?

**Comment by LtqxWYEG** [comment] 2020-10-02 07:35
Wow... yes it was `dom.IntersectionObserver.enabled`. But it wasn't set in my user.js. (Commented out) I never set it myself.
Maybe it was FALSE in an older version of ghacks and commenting it out was not reverting it back to true?

If that is the case, then you need to be careful about what you comment out and maybe revert the setting in one version before permanently leaving it out.

Thank you

**Comment by Thorin-Oakenpants** [comment] 2020-10-02 07:54
I suggest you run the prefsCleaner since it seems it's been up to 12 releases since you cleaned up programatically

> and maybe revert the setting in one version before permanently leaving it out

That's a good point, but it adds way more workload. And it **wouldn't work** if the default pref value differs across platforms (which should be super rare). And it **wouldn't work** if users skipped a release. And it **wouldn't work** for ESR users (who can skip up to 12 releases now) - although ESR users know a shitload has happened and generally one would expect they run the prefs cleaner - and, it wouldn't cover **removed** items. That is, we would have to treat removed items the same

ATM, we provide a changelog each release, and we provide a prefs cleaner script (it resets **all** prefs in the user.js and then on restart the active ones get reapplied), and we have some cleanup "scratchpad" scripts to also cover everything we removed (kept up to date) and everything deprecated (up to ESR)

I would prefer that users take responsibility for updating and we provide tools to help clean up: otherwise it gets too complicated

> Maybe it was FALSE in an older version of ghacks

It's always been false ... in was in v68 that it flipped to inactive (i.e commented out) #775

**Closed** 2020-10-02 07:56 UTC
Labels: FYI

**Comment by LtqxWYEG** [comment] 2020-10-02 14:23
`It's always been false`
Oh. Hm... But according to FFs about:config "True" is the default value. At least now. I guess that changed, huh?

I'll definitely try out prefsCleaner, of which I didn't knew it existed. :P (I guess that is also kinda new? The last time I read anything here was around v70)

**Anyway. Thank you all very much!**

**Comment by Thorin-Oakenpants** [comment] 2020-10-02 15:21
> according to FFs about:config "True" is the default value

It's always been false **in the user.js*** - i.e the pref value has always been false, the pref being commented out or not changed. Firefox adds prefs like these for testing, so they can enable it for say Nightly but not Release .. and then they flip the switch and let it ride the train (to release)

generally speaking - we don't include prefs and enforce their defaults (by making them uncommented out), otherwise we'd end up with a user.js with 2000 prefs which is a waste of time. A few items are enforced at default, and a few are there for the info factor - otherwise it's all about changing FF's defaults

> I guess that is also kinda new?

[v1.0 released](https://github.com/arkenfox/user.js/commit/fbd9f344af3cb6d0fb320de57497278887cc4b83) in Dec 2017 .. almost three years ago. In Dec 2017, Firefox 57 was released

**Comment by LtqxWYEG** [comment] 2020-10-02 16:16
Hm okay. Actually, while you're here, I had some issues after running prefsCleaner, that don't justify opening a new issue.

I found that Pocket was enabled, as well as "Recommend extensions as you browse" and "Recommend features as you browse" and "Block dangerous and deceptive content" and its subsidiaries. Aren't they all a privacy issue?

**Comment by Thorin-Oakenpants** [comment] 2020-10-02 17:30
because they're optional and commented out in section `5000: personal`. The prefsCleaner is only doing what its designed to do - reset everything. And the user.js is only doing what it's meant to do - set prefs that are not commented out.

If you want to modify the user.js, then append an overrides section

> Aren't they all a privacy issue

No.
- Pocket on Activity Stream is curated locally, and we disabled AS anyway. Pocket the service (saving stories to read later etc) does nothing unless you sign up for an account.
- Recommended extensions/features as you browse is pulled from local data - same with snippets in  case you ask
- SB is not disabled as it's a security feature - read the section header. We disable one part of it (real time binary checks with google) - otherwise everything else is not a privacy issue - **read the section header**

read the wiki

**Comment by LtqxWYEG** [comment] 2020-10-02 18:38
`    read the section header

read the wiki`

😛

OK :)
