### ISSUE TITLE
Is FPP used on RFP exempted sites? (when both are on?)

### ISSUE THREAD

**Issue by zdat** [arkenfox/user.js#1915] opened 2024-11-14 22:08 UTC
I have sites that are excluded from RFP.

```
user_pref("privacy.resistFingerprinting.exemptedDomains");
user_pref("privacy.resistFingerprinting.testGranularityMask", 4);
```

On these domains, does FPP instead take RFP's place? (when both are on)

Thanks.

---
edit by thorin

so the answer is - for these three current FPP protections - that RFP exemptions do NOT fall back to using FPP
- see https://github.com/arkenfox/user.js/issues/1915#issuecomment-2539889421

**Comment by Thorin-Oakenpants** [comment] 2024-11-17 09:52
testGranularityMask doesn't even exist, and I assume your exemptedDomains pref above actually has a value

Some RFP stuff is not per eTLD+1 - framerate is one, and I think css is also affected. So there may be quirks. And RFP isn't really supported upstream.

That said, if RFP is exempted then I would expect the site to fall back to using FPP if it is enabled (ETP Strict, FPP pref, PB mode)

@tomrittervg if you want to add anything

**Comment by tomrittervg** [comment] 2024-11-18 04:58
Ooooh good question.  I had never considered this. Or at least I don't remember consciously considering it.  The two questions are: "**What makes the most sense to happen?**" and "**What actually happens?**"

"**What makes the most sense to happen?**" - Thorin thinks if you have RFP and FPP enabled, and exempt something from RFP, then FPP should apply.  I can see that from the point of view that "The pref says RFP, it doesn't say FPP - so why would it exempt you from FPP?".  That's reasonable, although I'm not sure if he thinks it should do this because of that reason, or because of a deeper philosophical reason.  

Philosophically, for me, if you've disabled RFP for a website, you've really gone out of your way to disable protections on that website, for some good reason.  Probably to make it work.  If we didn't disable FPP also, you would need to go out of your way to figure out how to disable FPP for the website _also_.  That seems confusing.  It can also be a problem*.

"**What actually happens?**" - This is easier.  [This says](https://searchfox.org/mozilla-central/rev/f8488adfb9c3e25a80ba6a21e04950d58165e956/dom/base/nsContentUtils.cpp#2606-2623) that if a domain in the list is exempted - _and if_ it's a subdocument, its top level domain is also exempted - then the domain is exempted from both RFP and FPP.  

FWIW there is a related exemption. If a user disables ETP on a website, this will exempted it from FPP.  However, it [will not](https://searchfox.org/mozilla-central/rev/f8488adfb9c3e25a80ba6a21e04950d58165e956/dom/base/nsContentUtils.cpp#2306-2328) exempt it from RFP.  I didn't really build this as a philosophical statement, I built it more as "I wouldn't want people to accidently disable RFP via a UI element. If they want to disable RFP, they're going to have to dig into the prefs for it.".  My long term goal has always been to expose UI to selectively disable RFP on websites, and doing it via the ETP toggle might just be the way to do it. But I haven't tackled that project yet.

\* With the above paragraph of context, I can explain the problem better. If you want to disable FPP for a website, the only way to do it is via the ETP exemption.  You _might_ be able to do that buried in about:preferences somewhere, but the typical way to do it is with the ETP toggle.  And if you don't _have_ an ETP toggle, because say for example you're in Tor Browser and ETP isn't enabled, then you can't do that.  At least not easily.

**Comment by Thorin-Oakenpants** [comment] 2024-11-18 08:51
> Philosophically, for me, if you've disabled RFP for a website, you've really gone out of your way to disable protections on that website, for some good reason. Probably to make it work. If we didn't disable FPP also, you would need to go out of your way to figure out how to disable FPP for the website also. That seems confusing. It can also be a problem*.

true, except FPP is supposed to be super compat with interventions. I just assumed this is what happened because ... 

when we exempted RFP Canvas it fell back to FPP subtle randomization and we had to get that changed

--

for simplicity I think if you use RFP then we fall back to nothing is best, which sounds like **What actually happens**

**Comment by Thorin-Oakenpants** [comment] 2024-11-18 12:12
> **What actually happens**

anyway, the easiest way to answer this question is to test - because what actually happens may not be **what tom expects happens**

I'm just going to use nightly FF and only test using ETP Strict in a normal window. This is how arkenfox is set up and how I suspect the bulk of FPP users are using FF.

FPP only protects a few items and can vary per platform
- canvas
- fdlibm for trigometry - platform and version specific rolling out now
- kBaseFonts and kLangPackFonts
  - e.g. mac has no `kLangPackFonts` so RFP fonts == FPP fonts: you will see no difference

So first we need a control - i'm on wwindows - FF on ETP standard, no RFP
```
DOCUMENT: canvas: 38fe5952

{
  "getImageData": "trustworthy",
  "getImageData_solid": "trustworthy",
  "isPointInPath": "db0e3f08",
  "isPointInStroke": "a77e328a",
  "toBlob": "3afc375a",
  "toBlob_solid": "56ea6104",
  "toDataURL": "3afc375a",
  "toDataURL_solid": "56ea6104"
}


fonts detected: 5252a091 [190] [✗ 115 RFP]

trig: 7a7326dd [details] [✗ RFP]
```

now lets turn on ETP Strict
```
DOCUMENT: canvas: 098c407f

{
  "getImageData": "protected | persistent | FPP | rgb",
  "getImageData_solid": "trustworthy",
  "isPointInPath": "db0e3f08",
  "isPointInStroke": "a77e328a",
  "toBlob": "protected | persistent | FPP",
  "toBlob_solid": "56ea6104",
  "toDataURL": "protected | persistent | FPP",
  "toDataURL_solid": "56ea6104"
}

fonts detected: c17d4001 [173] [✓ FPP]

trig: d240b02e [details] [✓ RFP]
```

now let's turn on RFP
```
DOCUMENT: canvas: 0444d276

{
  "getImageData": "protected | per execution | RFP",
  "getImageData_solid": "protected | per execution | RFP",
  "isPointInPath": "protected | persistent | RFP",
  "isPointInStroke": "protected | persistent | RFP",
  "toBlob": "protected | per execution | RFP",
  "toBlob_solid": "protected | per execution | RFP",
  "toDataURL": "protected | per execution | RFP",
  "toDataURL_solid": "protected | per execution | RFP"
}

fonts detected: 5d085a76 [75] [✓ RFP]

trig: d240b02e [details] [✓ RFP]
```

now lets exempt `https://arkenfox.github.io` from RFP
- e.g. https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42125#note_3051098
```
DOCUMENT: canvas: 0444d276

{
  "getImageData": "protected | per execution | RFP",
  "getImageData_solid": "protected | per execution | RFP",
  "isPointInPath": "protected | persistent | RFP",
  "isPointInStroke": "protected | persistent | RFP",
  "toBlob": "protected | per execution | RFP",
  "toBlob_solid": "protected | per execution | RFP",
  "toDataURL": "protected | per execution | RFP",
  "toDataURL_solid": "protected | per execution | RFP"
}

fonts detected: 5d085a76 [75] [✓ RFP]

trig: d240b02e [details] [✓ RFP]
```

so seems to me as if RFP exempted sites is totally broken

**Comment by Thorin-Oakenpants** [comment] 2024-11-18 12:14
@tomrittervg so seems to me as if RFP exempted sites is totally broken

**Comment by Thorin-Oakenpants** [comment] 2024-11-18 12:21
personally, I would like to see the pref and and related code removed: complicates things? footgun? not-really-supported = we locked it in TB

**Comment by Thorin-Oakenpants** [comment] 2024-11-18 12:30
IDK - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42125#note_3051098 - I can't even replicate this in TB13 or TB14 - am I don't something wrong?

**Comment by Thorin-Oakenpants** [comment] 2024-12-12 03:22
FF133 new profile
- all tests done in a new tab after closing the previous one
- the first `font` item is a smaller fontFaces test which TZP only does for windows (at the time of writing)

ETP standard:  🗸 nothing protected

```
canvas: 38fe5952 (this means they are not tampered with)
 fonts: aeee7c38 [39] [✗ 19 RFP]
 fonts: 5252a091 [190] [✗ 115 RFP]
```

ETP Strict: 🗸 all FPP working (fonts and some canvas)
```
canvas: 098c407f (expected FPP)
{
  "getImageData": "protected | persistent | FPP | rgb",
  "getImageData_solid": "trustworthy",
  "isPointInPath": "db0e3f08",
  "isPointInStroke": "a77e328a",
  "toBlob": "protected | persistent | FPP",
  "toBlob_solid": "56ea6104",
  "toDataURL": "protected | persistent | FPP",
  "toDataURL_solid": "56ea6104"
}
fonts: 400a92e9 [25] [✓ FPP]
fonts: c17d4001 [173] [✓ FPP]
```

RFP (and ETP Standard) = 🗸 all RFP working
RFP (and ETP Strict) = 🗸 all RFP working
```
canvas: 0444d276 (this means all RFP protected)
 fonts: ecf709ad [20] [✓ RFP]
 fonts: 5d085a76 [75] [✓ RFP]
```

so far so good ... control tests look fine

RFP (and ETP Standard)
- add exemption `https://arkenfox.github.io`
   - does not work
- add exemption `*arkenfox.github.io`
   - does not work
- restart FF (with either exemption string)
   - does not work

`does not work` means we still got all of RFP's protections

**Comment by tomrittervg** [comment] 2024-12-12 13:41
> add exemption https://arkenfox.github.io
>    does not work

I can reproduce this

> add exemption *arkenfox.github.io
>    does not work

I can reproduce this

What if you make the exemption "arkenfox.github.io" ?  That works for me.  

 - arkenfox.github.io - Works
 - github.io - does not work
 - *.github.io - works
 - *.arkenfox.github.io - does not work
 - *arkenfox.github.io - does not work

**Comment by Thorin-Oakenpants** [comment] 2024-12-12 16:10
IDK, will test later .. but look at this picture -> https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42125#note_3051098

**Comment by Thorin-Oakenpants** [comment] 2024-12-12 19:54
so back to here - https://github.com/arkenfox/user.js/issues/1915#issuecomment-2482869332

the easiest way to answer this question is to test - because what actually happens may not be what tom expects happens

using nightly on windows
- FPP protections (ETP Strict)
   - fonts (level 2), trig and some canvas - checked, working
- RFP enabled (ETP Strict still on)
   - fonts (level 1), trig, and all canvas as RFP - checked, working
- RFP enabled (ETP Strict still on) but added `arkenfox.github.io` to exempted
   - fonts, trig, all canvas - zero protection

So the answer is - for these three current FPP protections - that RFP exemptions do NOT fall back to using FPP

**Closed** 2024-12-12 19:56 UTC
Labels: fingerprinting, answered
