### ISSUE TITLE
FreshRSS: dynamic toDataURL favicon [solved: icon created in JS via canvas - RFP protects this]

### ISSUE THREAD

**Issue by Offerel** [arkenfox/user.js#1317] opened 2021-12-28 13:32 UTC
Browser version: 95.0.2

If i use arkenfox user.js, this seems to break generating the favicon for FreshRSS. I have opened an issue also in the repository for FreshRSS, but maybe someone here has a workaround until we get a fix for FreshRSS. You can fin the issue at https://github.com/FreshRSS/FreshRSS/issues/4091
![Broken Favicon](https://user-images.githubusercontent.com/14041522/147571141-e85ffef7-a0a5-4f03-9e28-0f128b81b2e6.png)
![Correct Favicon](https://user-images.githubusercontent.com/14041522/147571263-5ddfcc55-996c-4361-a26d-9fbd75ce2865.png)

Using a Firefox profile without arkenfox user.js, did not have the issue.

**Update:** I have now set `user_pref("browser.shell.shortcutFavicons", true);` where this issue seems to be not occur. I'm not realy sure, if this solves the issue completely, but it seems so.

**Comment by Thorin-Oakenpants** [comment] 2021-12-28 14:34
Where is the icon coming from? What is the URL, is it an extension page?

**Comment by Thorin-Oakenpants** [comment] 2021-12-28 14:35
I do not use this extension or whatever it is. You need to give full STR

**Comment by Offerel** [comment] 2021-12-28 15:18
It's not an extension. It's a webapplication, a RSS feed aggregator. There is no url as an official service, because you install it on your own server.  But you can find the source code at the issue link, I have posted. Maybe this helps to identify where the issue comes from.

**Comment by Thorin-Oakenpants** [comment] 2021-12-28 16:19
It's a tab in your browser right? So what is in the urlbar (that's what I mean by URL)

**Comment by Offerel** [comment] 2021-12-28 16:21
Ahhh ok, now I understand. that's a private url you can only reach internally in my own network.

**Comment by Thorin-Oakenpants** [comment] 2021-12-28 16:33
I wanted you to tell me it was localhost, I wanted you to tell me what that the URL is, exactly. I wanted you to look at the page source and tell me what the icon source is. But instead I just get cryptic answers. It's not on me to know what the heck is going on and second guess everything, sorry

Provide some details

**Comment by Offerel** [comment] 2021-12-28 16:46
No prob. I try to answer as best as possible.

The url in my address bar is https://testinstance/news/i/

Looking in the source of the generated page, reveals a favicon as data URI. I don't have the complete data uri here, because I'm writing from my phone instead the desktop. I can give you the exact data URI later.

I can only confirm, that set browser.shell.shortcutFavicons to true, will solve the issue for now. But i don't know if this is only a temporary fix. I have also no idea what this setting do or change, if set to true instead of false (in privacy sense). The description is a little bit vague for me.

**Comment by Thorin-Oakenpants** [comment] 2021-12-28 17:11
The info is in the user.js!!!

https://github.com/arkenfox/user.js/blob/2787da7f90b31b19d3549b61a77210b79bd1166b/user.js#L451-L455

I'm trying to find out why a shortcut setting affects your website icon

**Comment by Offerel** [comment] 2021-12-28 20:20
I have switched back to the standard value (false) and the favicon is working. For me, this looks like, it is a caching issue. However, changing the value to true, seems to refresh or null the cache, maybe the shortcutCache. 

At least for me, the issue is solved. Feel free to close the issue,if you want.

BTW: The icon in source looks like (correct version):
`<link rel="shortcut icon" id="favicon" type="image/x-icon" sizes="16x16 64x64" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACLElEQVQ4jXWTQWtTQRSFL4gWorsq5icoBXf5IaW/IBHjqtBqVl2Je5f9AW7spqs3rU2VvBRFSCE0E9JaMJQqNbU64YXGxJaXvPu5eC9JU/TAXQzMvXPOuWdErsFUSZl62xjr1FiHZH0k5+utp+Xi3Ivynev3p7BRd1vGOryao3wY8LnVY3mtycOVCpItITmfm/md9/9sNtb9MtZx0OoBoKp0+gMqR+cMIwVgea2J5HxuPPbb081199ZYR6cfEqlSbLQx1nFFArOLHwiHSuXoHMn5zDzZeZdoPk2NXo5U8WoOzzq+B5eoxkxef/oRS8iWCIc6ZvKoUL8tm/W28WoOgGKjjWcdqjHlqxhEimRL3F38CIBkS8zkd7bEWKflwwBVxVjHSXAJwJvK2fjVtd0zgJhJzmcYKQ9WKkjOV+n0B/wJI4ZRbNoI1eMu1a9JHXcBiFSRrM/u0XksI+sj447VVZDJMbx3Pz6L8O3lq2QzEJs94KDVi00GYsHp9GRAswkiMYvjLkEvBOAkuMAkHpUPA4x1KkCHQgEymcmAEZtRJbnwrGO70QbAqzk2684TYA8RKBanJIyRyTB89hwvSWikyn5C31RPU0I+f8bS0uX/BoTzC4TzC2w32kSqBL0QYx0b1m2IiAizs+EU3XSasaSEAYUCAPut36OE/hzHGKgCVdbXv0wxGJmaTtO9GODV4mibujNT/2A8YFJ7QGe0nU5/QKc/wFjnmepp6von/AtfT9hI44TWgAAAAABJRU5ErkJggg==">`

The broken icon data URI was a lot shorter.

**Comment by Offerel** [comment] 2021-12-28 21:44
The FreshRSS developer has send me a link where the favicon is generated. I found that it is generated with a canvas element in some javascript `const canvas = document.createElement('canvas');`

If i make an exception for canvas elements on the freshrss url via url bar, this works as a workaround until i found a way to generate a dynamic icon without using a canvas element. This does not explain, why `user_pref("browser.shell.shortcutFavicons", true); ` will work also as a workaround. But so far, this is not an arkenfox issue at least in my eyes. I will update this issue here, if i found a better way for FreshRSS.

BTW: I'm not the developer of FreshRSS, only a user...

**Comment by Thorin-Oakenpants** [comment] 2021-12-29 04:36
Right. So my initial reaction was RFP, but the image doesn't look exactly how it should - it's stripey with different colored bands, rather than a wavy "same" color
- https://arkenfox.github.io/TZP/tests/canvasnoise.html
- ![example](https://user-images.githubusercontent.com/16656956/147627109-e3128c45-f201-4611-be72-e674415d04d7.png)

And the mention of `browser.shell.shortcutFavicons` made me pause. And I didn't want to suggest RFP, because I would rather dig into the cause, but I suspected it would be to do with principals

Hence I wanted to know who and how the icon was being set, and what the URL was and the icon data. You supplied me with the one that wasn't all screwed up, which is a bit useless - I wanted the one that was "damaged"
- https://arkenfox.github.io/TZP/tests/canvasspoof.html
- ![example2](https://user-images.githubusercontent.com/16656956/147627277-21c1a63e-10d2-4af5-999c-faceae7b5146.png)
- > The broken icon data URI was a lot shorter.
- ^ indeed, this is the one I wanted

`browser.shell.shortcutFavicons` is not a solution IMO, it is a symptom of something else. It'll be to do with some code path where favicons are not affected by RFP's canvas, but when blocked it causes a different path and this is affected. I wonder if I can STR this on a live website

> If i make an exception for canvas elements on the freshrss url via url bar, this works as a workaround

This is your answer, until it is addressed, if ever, upstream. Setting a canvas site exception here is perfectly valid - it's your internal site, and you are not fingerprinting yourself. If it happens on live web sites, Personally, I wouldn't consider a broken favicon as good enough justification, it's just an annoying visual

Don't close this issue, I want to follow up on it

**Comment by Minimalist73** [comment] 2022-01-02 18:15
@Thorin-Oakenpants Just in case you want a live website for your own test, I get this exact same behavior on every Gitlab Pipeline page (ex: https://gitlab.com/gnutls/gnutls/-/pipelines/435057038), reloading page generate a new favicon too.

**Comment by Offerel** [comment] 2022-01-02 19:32
True, that's the same effect. For FreshRSS, i have created a Pull request for a workaround. In this, i check the computed string for length. If it's longer as 180 characters, canvas element is allowed, if not, then its not allowed and you get a broken favicon. In this case FreshRSS uses now a fallback icon and not the dynamic one.

**Comment by Thorin-Oakenpants** [comment] 2022-01-02 21:32
>  If it's longer as 180 characters, canvas element is allowed

FYI - in FF96+ [they changed the png compression](https://bugzilla.mozilla.org/buglist.cgi?bug_id=1724331,1737038) - length can be as high as 190 with RFP

However, this does not take into account extensions or other browsers modifying toDataURL - although most are probably only slightly modifying it and not enough for the optical eyeball to notice (Brave for example moves about half of each of the RGB channels by +/- 1, altering about 80-85% of the pixels)

e.g. an example of Brave with shields on from [here](https://arkenfox.github.io/TZP/tests/canvasnoise.html)
```
cells changed: 319 (out of 400)
channels changed: 3 [rgb]
channel counts: r: 189, g: 179, b: 198, a: 0
combos altered: 7 [b, g, gb, r, rb, rg, rgb]
combo counts: {"gb":66,"rb":64,"rg":55,"b":37,"r":39,"rgb":31,"g":27}
```

---

When I labelled this as a possible bug, it was that I was concerned that RFP had a leak, not that it broke a dynamic icon served by canvas :)

**Comment by Thorin-Oakenpants** [comment] 2022-01-02 21:37
here's the RFP code for lengths
- https://github.com/arkenfox/TZP/blob/666db95a4a852757c2f220edfd4f2756bae61620/tests/canvasrfp.html#L63
   - as you can see for FF96+ the length varies from 174 to 190
- https://github.com/arkenfox/TZP/blob/666db95a4a852757c2f220edfd4f2756bae61620/tests/canvasrfp.html#L88
   - for FF78-95 the length varies from 162 to 174

**Comment by Thorin-Oakenpants** [comment] 2022-01-02 21:38
pinging @Offerel  - read the above two posts, not sure if you're subscribed

**Comment by Thorin-Oakenpants** [comment] 2022-01-02 21:54
https://gitlab.com/gnutls/gnutls/-/pipelines/435057038
- in my nightly where I have never visited this particular page (but I have visited gitlab before)
- note I am sanitizing everything on close, so IDK if that means favicons

one
- RFP is on
- `browser.shell.shortcutFavicons` is default true
- test: reloads: icon is always RFP'ed
- set `browser.shell.shortcutFavicons` to false
- I restarted
- test: reloads: cion is always RFP'ed

two
- now relax canvas so something maybe gets cached
- revoke site exception for canvas
- reload
- delete bookmark which has fubared icon
- disable RFP, rebookmark with good icons
- keep fiddling and testing

with RFP, I cannot make the tab icon fall back to a cached one or be anything other than a RFP one - so IDK anymore. Pretty sure any webcontent principal that attempts to use toDataURL when RFP is on will always get a random result

**Closed** 2022-01-04 01:43 UTC
Labels: answered
