### ISSUE TITLE
Wiki: Outdated Extension Recommendation?

### ISSUE THREAD

**Issue by kylejcharlton** [arkenfox/user.js#1326] opened 2022-01-10 00:21 UTC
So I have been using some of the extensions that are recommended in the wiki at [4.1-Extensions](https://github.com/arkenfox/user.js/wiki/4.1-Extensions). I noticed that the extension '*Smart Referer*' and its provided whitelists have not been updated in quite some time (almost 2 years according to [GitLab](https://gitlab.com/smart-referrer/smart-referer)). I only bring this up as this extension has been causing breakage for some sites (one example being the login page for Oracle Cloud at cloud.oracle.com) due to an unmaintained whitelist. This probably would not be an issue if there were any recommended third party lists, but may still present a problem.

Should this extension still be recommended as a result of lack of updates or even obsolescence?

**Comment by Thorin-Oakenpants** [comment] 2022-01-10 01:55
I personally don't use it. My understanding is you just need to add exceptions: choose a mode and then add exceptions/rules. There's nothing stopping you, AFAICT, from unbreaking anything - e.g. if you were in strict mode, how do you unbreak the few sites you need to unbreak

IDK if it needs an upkeep, I don't think any changes in the web extension's API has been affected, but I do get that the dev is probably dropped it and moved onto other things as a priority

https://addons.mozilla.org/en-US/firefox/addon/smart-referer/
> To workaround (rare) breakage, a whitelist of related domains is regularily downloaded (24h) and applied in the background. You may view and update the current version of this whitelist [here](https://gitlab.com/smart-referrer/smart-referer/-/blob/gh-pages/whitelist.txt).
> 
> Further information on advanced configuration options, writing your own whitelist entries and contributing is available in the [repository README file](https://gitlab.com/smart-referrer/smart-referer/-/blob/master/README.md).

the [whitelist](https://gitlab.com/smart-referrer/smart-referer/-/blob/gh-pages/whitelist.txt)
- 21 items
- it was never big to start with
- my guess was it was designed to auto-unbreak some common, high traffic sites
- according to the old AMO description .. the breakage was rare
- it's just a default whitelist

unless I'm missing something and the whitelist was because it couldn't be done in the extension? IDK

also, emphasis mine

> Further information on advanced configuration options, **_writing your own whitelist entries_** and contributing is available in the [repository README file](https://gitlab.com/smart-referrer/smart-referer/-/blob/master/README.md).


[readme](https://gitlab.com/smart-referrer/smart-referer/-/blob/master/README.md)
- read it
 - > The default whitelist tries to minimize the impact of this extension on everyday web surfing while still providing the maximum referer privacy possible under these circumstances. See the default whitelist inclusion guidelines as this may not be what you want.
- click links
  - > [A website is not working, what should I do?](https://gitlab.com/smart-referrer/smart-referer/-/blob/master/README.md#a-website-is-not-working-what-should-i-do)
   - you can try adding an exception for the domain

---

Not asking anyone in particlar - but I don't use Smart Referrer. Can you add exceptions in Easy Mode. What is Easy Mode. Is Easy Mode the default? Maybe we should edit the wiki to say use Strict Mode and add exceptions. Is there anything in the gitlab issues that indicates the extension cannot work as advertised and users can't unbreak sites

Assigning to everyone else

**Comment by Nallua** [comment] 2022-01-10 02:53
This is Smart Referrer's options page with the defaults, for reference.

![Screenshot 2022-01-09 214137](https://user-images.githubusercontent.com/95902779/148712794-b2ae9f8d-0ed5-42a3-b8d8-ae15e6cd06a2.png)

>Can you add exceptions in Easy Mode. What is Easy Mode. Is Easy Mode the default?

I'm assuming Lax is what you're referring to as Easy Mode.

**Comment by Thorin-Oakenpants** [comment] 2022-01-10 04:05
Whatever it's called. So smart referrer's default is "lax". 

So on AF we are
```js
/*** [SECTION 1600]: HEADERS / REFERERS
   Expect some breakage e.g. banks: use an extension if you need precise control
                  full URI: https://example.com:8888/foo/bar.html?id=1234
     scheme+host+port+path: https://example.com:8888/foo/bar.html
          scheme+host+port: https://example.com:8888
   [1] https://feeding.cloud.geek.nz/posts/tweaking-referrer-for-privacy-in-firefox/
***/
user_pref("_user.js.parrot", "1600 syntax error: the parrot rests in peace!");
/* 1601: control when to send a cross-origin referer
 * 0=always (default), 1=only if base domains match, 2=only if hosts match
 * [SETUP-WEB] Known to cause issues with older modems/routers and some sites e.g vimeo, icloud, instagram ***/
user_pref("network.http.referer.XOriginPolicy", 2);
```

we're using HTTPS-Only Mode so I don;t think scheme will matter for Smart Referer (in case scheme is not used in either/or mode)

so what is the difference between FF's `2` and SR's `Lax` - you guys tell me.

Still assigned to everyone else

**Comment by Nallua** [comment] 2022-01-10 04:54
I don't actually know how to check the referrers being sent (if someone can tell me I'd be happy to), but just judging from the descriptions in SR's settings menu, my assumption is that `Lax` is FF's `1` and `Strict` is `2`. That being the case, the only time I can see an advantage to Smart Referrer over what Arkenfox does is when you actually need a whitelist/exceptions. Maybe it'd best to consider moving SR to the Maybe section on the Extension page, provided someone can confirm it still functions as intended?

**Comment by crssi** [comment] 2022-01-10 08:50
SR still works as intended.
I don't see the reason that is should be updated, since it just works.

I guess that if OP thinks that there is some sites missing then there are 3 options:
1. Open issue on SR site
2. Add a rule
3. Create its own rule "file" and point SR to.

Its the same logic as with uBO... if you are missing a rule then make one, if you are missing a filterlist then make one.

**Comment by Thorin-Oakenpants** [comment] 2022-01-10 14:17
Exactly. That's what I said: just add rules, FFS

But I do wonder a tiny bit what the exact downgrade from AF level to SR's lax is _exactly_, both in terms of 1601 (when to send) and 1602 (what to send). Does 1601+1602 even limit SR in any way, or can it do what the F it likes since it's the last to touch it?

**Comment by crssi** [comment] 2022-01-10 15:52
`network.http.referer.XOriginPolicy` wins over SR.
So if you use SR then `network.http.referer.XOriginPolicy` must be set to `0`

Cheers

**Comment by Thorin-Oakenpants** [comment] 2022-01-11 01:47
OK, so `network.http.referer.XOriginPolicy` must nix the information early on, and if affects the Web Ext API or something

SR wouldn't serve a purpose if it didn't improve from defaults (IDK if 1602 still applies to Web Ext), so it must be blocking more referrers than doing nothing. So while it SR's default is a downgrade, it's better than nothing

But how fucking lax is lax: by the looks of it, it only allows eTLDs+1 to talk to each other, which is at least something: probably a good balance for those that find they need to revert 1601

current mentions
- wiki extensions page just lists SR with no context
- wiki implementation page says ... 1601 .. "Change to suit and consider installing an extension"
- user.js 1600s section header says "Expect some breakage e.g. banks: use an extension if you need precise control"

What I could do is
- 1601, with the setup tag - should have the extension mention, so it's tied to changing the pref etc for troubleshooters
- wiki extensions page - SR could have a bullet point e.g. "if you have reset the 1601 x pref due to usability and website breakage"

**Comment by Nallua** [comment] 2022-01-11 10:20
For the wiki extensions entry, I suggest the following:
- A bullet point explaining that if you don't need exceptions or use a separate profile for the sites you need a less strict `XOriginPolicy` value on, it's redundant at best with Arkenfox's referrer tweaks.
- A bullet point explaining that 1601 has to be overridden to `0` for SR to actually work. This'll hopefully prevent users from keeping that pref at 2 under the assumption that SR will "win" and it doesn't matter what it's set to.
- A bullet point telling/reminding/warning users that if they do use SR, they need to learn how to add their own exceptions to the whitelist to actually get the benefit from using it.

In Arkenfox itself, maybe the setup tag could say that if you're setting 1601 to 0 because a website you use breaks with 2 or even 1, you should consider the extension so you're not forced into an all or nothing situation with that particular pref?

**Comment by g-2-s** [comment] 2022-01-11 13:24
I have to use SR and `network.http.referer.XOriginPolicy` at default `0` thanks to one site, my settings are:

- default whitelist _`unchecked`_: this is because from my experience the default whitelist is basically useless; the site I need this addon for is on that list but it still doesn't work, it only works if I add the rule/exception manually.
- rewrite mode set to _`Send nothing as referer, looking like a direct hit`_
- domain name matching strictness set to _`strict`_

No problems encountered with these and as far as I remember from reading in a issue here these are basically the same as setting `network.http.referer.XOriginPolicy` to `2`.

**Comment by remyabel2** [comment] 2022-01-23 07:28
Note that smart referer potentially connects to the cloudflare IPFS gateway to download the whitelist which logs your IP. 

> https://gitlab.com/smart-referrer/smart-referer/-/blob/master/assets/const.js#L14

I imagine most people would find this surprising or undesirable.

**Comment by kylejcharlton** [comment] 2022-01-23 07:36
It's possible you can use the whitelist override to point to the raw file on GitLab, but it seems strange to need to do that in the first place...

**Comment by Thorin-Oakenpants** [comment] 2022-02-25 10:49
done, enjoy the master craftsmanship of your almighty naked overlord, you dirty great unwashed masses

**Closed** 2022-02-25 10:49 UTC
