### ISSUE TITLE
Netflix Error F7121-1331 on Mac/Linux [solved: RFP's HTTP Header is spoofed as Windows & NF no longer chills] [1610762]

### ISSUE THREAD

**Issue by anonimno1** [arkenfox/user.js#1321] opened 2022-01-06 13:58 UTC
Hello all,

I am running FF ESR91 from Debian Stable. Without user.js Netflix is playing fine. 
When I apply user.js (the version for ESR91) and the override recipe `user_pref("media.eme.enabled", true);` Netflix videos can not be played. They start loading (without the override they do not) and then Error F7121-1331 is shown.

Does anything else need to be overriden?

**Comment by Thorin-Oakenpants** [comment] 2022-01-06 14:20
does the test work?
https://github.com/arkenfox/user.js/blob/7016c2050d20d53242c30eaf0b3beca947e172f6/user.js#L652

I want to make sure that you actually downloaded the `gmp-widevinecdm` files

**Comment by Thorin-Oakenpants** [comment] 2022-01-06 14:28
Assuming the test works: here are some ideas
- when on Netflix go Control-I > Permissions tab > Cookies
  - you want it to be `Allow`
  - AF uses session cookies, so uncheck Cookies > Use default and it should show `Allow for Session` as checked, change that to `Allow`, reload

Also - https://support.mozilla.org/en-US/questions/1327509 - which indicates that Private Browsing windows have this issue, so make sure you're not always starting in PB mode (this is what made me think cookies might be the issue)

**Comment by anonimno1** [comment] 2022-01-06 14:50
https://bitmovin.com/demos/drm works, but Netflix doesn't. Also after allowing Cookies as suggested,

BUT I will go another way. I will be using your user.js without changes for my default ESR FF and daily use.
When I need Netflix (or anything else DRM) I will use Flatpack FF.

Benefit? Default is private and secure, I allow DRM and other stuff only when needed.

THANK YOU for fast responses.

**Comment by fxbrit** [comment] 2022-01-06 23:32
the issue could be caused by RFP changing the user agent to ESR: iirc Netflix wants you to be on the latest version possible (can't test because I don't have an account, sorry).

**Comment by Thorin-Oakenpants** [comment] 2022-01-07 00:45
It shouldn't be the user agent: DRM has been supported for a long time and is updated even when the browser is not. Besides, ESR91 is not that old, and there would be a compat intervention or at least a record of bitter complaints

I want to know the cause - re-opening to remind me (and for anonimno1 to hopefully test without RFP) - or for anyone else with a NF account to test things

**Comment by Thorin-Oakenpants** [comment] 2022-01-07 08:26
after some [guggling the interwebs](https://en.wikipedia.org/wiki/Beforeigners) I would like to know if this fixes it
- Settings > General > Performance > 
   - uncheck `Use recommended performance settings`
   - this then will show you another options - check it - `Use hardware acceleration when available`
- Restart
- Test
- Undo changes

If this solves it, then we have an answer as to why it happens, but I don't recommend you change default perf settings, hence why I said to undo the changes

**Comment by Thorin-Oakenpants** [comment] 2022-01-15 05:26
ok, no-one able or willing to test that then .. closing

**Comment by crssi** [comment] 2022-01-15 07:24
I would do it, but l don't have Netflix account. 😢

**Comment by Thorin-Oakenpants** [comment] 2022-01-15 08:02
well, obviously if you don't have an account and thus the problem, no one expects you to. Was hoping OP would test since he said he was sticking with the issue and just going to use NF in a secondary browser

**Comment by yashomdighe** [comment] 2022-01-15 14:53
>     * Settings > General > Performance >
>       
>       * uncheck `Use recommended performance settings`
>       * this then will show you another options - check it - `Use hardware acceleration when available`
> 
>     * Restart

 I am having the same issue (Error F7121-1331). This did not fix it

**Comment by Thorin-Oakenpants** [comment] 2022-01-15 20:13
thanks. Are you also on Linux with ESR91?

**Comment by yashomdighe** [comment] 2022-01-16 05:51
I am on macos with 96.0.1. It also happens on linux. Yet to try out on windows. I started using user.js about two months ago so it also happened on that version of firefox (94 i think?).

**Comment by Thorin-Oakenpants** [comment] 2022-01-16 07:44
OK. So maybe it is to do with the user agent? One one to tell would be
- in a new profile, make sure Netflix works
- then clear everything (Ctrl-SHift-Del)
- enable RFP and retest Netflix - it should Error F7121-1331
- then clear everything (Ctrl-SHift-Del)
- then install a user agent extension [1] and "lie" about yourself being Firefox the real user agent (or close enough)
   - by that I mean, if you are FF96 on Linux, then show that
   - test what the agent says first - e.g. at TZP
   - test Netflix - if it works then it's not RFP per se, but NF being dicks and not using feature detection

[1] Am trying to find an easy to use extension but they're all a bit shit TBH, I guess Canvas Blocker is the easiest
- CB Settings > APIs > untick everything except Navigator API (note you can't untick canvas)
  - tick Navigator API
  - click Open (for navigator settings)
  - etc, you can just clilck your OS + FF and tghe version should already be `{real Firefox version}`

**Comment by yashomdighe** [comment] 2022-01-16 16:54
You are right. Netflix works when I report the real user agent when RFP is enabled.

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 01:44
just to keep you in the loop, I am nudging some devs upstream for their thoughts on version spoofing: as this is not the only time the version has caused issues

RFP exists primarily for Tor Browser but there are RFP protections not even used by TB: such as font protections, connection type, etc. But that doesn't mean it can't be made more compatible, even if that reason is lazy website code
- I find this Netflix one strange because it obviously works in ESR91 (and earlier)

TBA (android) is the only version that uses the release channel, other it uses ESR. So the spoofing is redundant for TB. But they do want to move to release at some stage (rather than hit these big backlogs of ESR changes I guess). You can't hide your version from advanced scripts, but that doesn't mean  RFP shouldn't make life harder. And on non-ESR there will be entropy with latency of updates: if everyone updates in a timely fashion it shouldn't really be an issue - but there would, in a best case scenario, always be two sets with simple userAgent sniffing - last stable vs new stable

So I don't know what the answer is. Personally I think we could do away with the version spoofing, at least on Firefox. If TBA wanted to keep the version changes only for flag days, then that could also be coded

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 01:56
note to self:
I actually wonder if it actually is the version, and not the other parts of navigator, or the HTTP header : as OP said `91.4.1esr` (linux) didn't work - spoofing as version 91 wouldn't make a difference, and I'm assuming NF works on ESR91

> I am on macos with 96.0.1. It also happens on linux. Yet to try out on windows.

http header is spoofed as windows

This would be easy to test. @fxbrit you know what to do

**Comment by yashomdighe** [comment] 2022-01-21 04:49
> So I don't know what the answer is. Personally I think we could do away with the version spoofing, at least on Firefox. If  TBA wanted to keep the version changes only for flag days, then that could also be coded

I will be happy to test anything if you need me to.

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 05:00
Cool, so on mac or linux, with RFP, I want you to only override RFP's http header (not the navigator userAgent bits). Do you need help to do that?

**Comment by yashomdighe** [comment] 2022-01-21 05:01
Yep I will

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 05:07
OK, try this instead
- FF on mac/linux, 96 or whatever
- new profile, RFP on, NF fails, cool
- clear everything (cntrl-shift-del)
- turn on CB, lie about the version but nothing else
- test header here: https://browserleaks.com/ip <-- scroll down to HTTP Header>UserAgent
- test NF: if it's broken then the issue is not the version but the platform

By using CB in testing earlier, it also corrects the header to match: so it's not conclusive

**Comment by yashomdighe** [comment] 2022-01-21 05:40
Testing on mac:
browserleaks reports this as the user agent 
**Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0.1) Gecko/20100101 Firefox/96.0.1**

This does not work. Still getting the same error. 

If i do not set the OS in CB, netflix just throws some HTML5 player error. The user agent reported by browserleaks in this case is 
**Mozilla/5.0 (undefined; rv:96.0.1) Gecko/20100101 Firefox/96.0.1**

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 06:05
Yeah that test is borked. I should be clearer

> Testing on mac: browserleaks reports this as the user agent **Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0.1) Gecko/20100101 Firefox/96.0.1**

RFP will always report mac, so I can only assume this is CB not configured correctly as per my instructions

> If i do not set the OS in CB, netflix just throws some HTML5 player error. The user agent reported by browserleaks in this case is **Mozilla/5.0 (undefined; rv:96.0.1) Gecko/20100101 Firefox/96.0.1**

ditto, we want to not spoof anything except the version. So RFP on and then spoof CB to match your OS (so the http header is no longer windows)

> If i do not set the OS in CB

I want you to enable RFP, in CB set the spoof to Mac + Firefox (this will set the OS including the HTTP header), then override the version to 91 (just like RFP)

**Comment by yashomdighe** [comment] 2022-01-21 06:20
Okay so I set  the OS as macos and FF version to 91. RFP is enabled with `user_pref("privacy.resistFingerprinting", true);` (That is the only pref in the user js for this profile). The user agent now is : 
**Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14.3; rv:91.0) Gecko/20100101 Firefox/91.0**

And netflix works

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 07:32
Right .. so that proves that the issue is the HTTP header's platform, not the version - thanks for testing

**Comment by fxbrit** [comment] 2022-01-21 09:21
so the mismatch between the `user-agent` field in the HTTP header and `Navigator.userAgent` is what's triggering netflix?

you talked about [version spoofing](https://github.com/arkenfox/user.js/issues/1321#issuecomment-1018085702), and there have been some on-going discussions at TB over the `user-agent` bit of the HTTP header in the past. I get the argument for passive vs active, but at least for FF wouldn't it make sense to show the real OS in that field as well?

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 09:38
no, the mismatch is not the problem, it is the lying about the platform. It just happens to be that RFP _**only lies about platform in the http header**_ - so NF is obviously using that to _do something_ and that something then creates an error

There are some things you cannot hide: engine, version, OS ... but that doesn't mean RFP can't make life hard for scripts. IDK why they did version spoofing considering at the time it was only for TB and TB was already ESR. They also went with two tuples (windows, android) - but this causes compat issues, so they changed JS to four tuples but left headers at two (which fits in nicely when JS is disabled such as TB slider on safest: but do note that OS can still be passively detected)

**Comment by tomrittervg** [comment] 2022-01-25 15:54
I tried complaining to netflix support about it, but they weren't able to file an engineering ticket about it :-/

**Comment by Thorin-Oakenpants** [comment] 2022-01-26 02:15
> I tried complaining to netflix support about it, but they weren't able to file an engineering ticket about it :-/

If they did they would mark it as WONTFIX, since RFP is breaking web standards

I think we need a `privacy.resistFingerprinting.tb` pref and if false don't spoof the version number (the number of FF users is massively higher than TB) or the HTTP Header's OS. The same can hold for other TB specific changes down the track that don't meet the same threat model

**Comment by Thorin-Oakenpants** [comment] 2022-01-28 15:00
I think we have some progress here, but unless @tomrittervg actions it (or feeds it to a first bug apprentice), it'll never happen and languish at P5, and that's understandable, not because it's a difficult patch (it's pretty simple IMO), but because RFP is for TB, and TB don't really want this (and it's moot given DRM is blocked and AFAICT this is about the only instance of HTTP Header spoofing causing an issue), and IDK if tom et al really want an extra code path/divergence

so IDK what will happen `¯\_(ツ)_/¯`

**Closed** 2022-02-21 02:40 UTC
Labels: firefox bug, answered

**Comment by Jerry1098** [comment] 2022-02-24 22:00
I have/had the same problem and kinda fixed it by using this add-on: [Netflix-1080p](https://addons.mozilla.org/en-US/firefox/addon/netflix-1080p-firefox/). It seems to be open-source: [here](https://github.com/TheGoddessInari/netflix-1080p-firefox). I don't really want to recommend using this kind of add-on, but its working for me and someone else might find it useful too.
