### ISSUE TITLE
cant join games in roblox.com

### ISSUE THREAD

**Issue by pafffii** [arkenfox/user.js#1496] opened 2022-07-05 14:39 UTC
Browser version: 102.0
OS: ggOS (twitter.com/getggos, discord.gg/ggos)

STR: 

You need an account to do this one but go to any game example https://www.roblox.com/games/9508087919/Apeirophobia-The-End-UPDATE and click on play.

error i got: https://ibb.co/68yvJ6Q

expected result: 
opens roblox and goes into game
https://ibb.co/G78KtTZ

important mention:
theres a guide on fixing this but i dont understand lmao (https://github.com/arkenfox/user.js/issues/1319)

**Comment by rusty-snake** [comment] 2022-07-05 14:42
> theres a guide on fixing this but i dont understand lmao (https://github.com/arkenfox/user.js/issues/1319)

https://github.com/arkenfox/user.js/issues/1319#issuecomment-1005483730:

> Setting the `network.http.referer.XOriginPolicy` to 0 and 1 seem to fixed my issue.

- Go to `about:config`
- Search for `network.http.referer.XOriginPolicy`
- Set it to `1`
- Try again
- If it works, add it to your `user-overrides.js`.

**Comment by Thorin-Oakenpants** [comment] 2022-07-05 14:44
duplicate of #1391

**Closed by Thorin-Oakenpants** 2022-07-05 14:44 UTC
Labels: invalid

**Comment by pafffii** [comment] 2022-07-05 15:22
> > theres a guide on fixing this but i dont understand lmao (#1319)
> 
> [#1319 (comment)](https://github.com/arkenfox/user.js/issues/1319#issuecomment-1005483730):
> 
> > Setting the `network.http.referer.XOriginPolicy` to 0 and 1 seem to fixed my issue.
> 
>     * Go to `about:config`
> 
>     * Search for `network.http.referer.XOriginPolicy`
> 
>     * Set it to `1`
> 
>     * Try again
> 
>     * If it works, add it to your `user-overrides.js`.

ty man
