### ISSUE TITLE
Does anyone know if/which user.js setting this is ...

### ISSUE THREAD

**Issue by privacyguy123** [arkenfox/user.js#1432] opened 2022-04-26 14:36 UTC
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox

🟪 REQUIRED INFO
  - Browser version & OS: FireFox 99.01/Windows 10 LTSC 2021
  - Steps to Reproduce (STR): vist the website, maybe it will load first time maybe it won't - after browsing 2 or 3 clicks deep = "access denied"
  - Expected result: website should work normally, like it does on Google Chrome on the same machine.
  - Actual result: 
![image](https://user-images.githubusercontent.com/50337995/165324366-5f5153d8-781f-4a12-af38-c2722e9b9518.png)
  - Console errors and warnings: Literally nothing of use ```This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.```
  - Anything else you deem worth mentioning: I have ruined my sanity trying to find what causes this. Clean install Windows with TOTALLY DEFAULT settings to rule out Windows "tweaks" for e.g. I have narrowed it down to specifically FireFox with this user.js, resistfingerprinting off because it breaks everything, FireFox in "safe mode" aka 0 addons also gets hit with access denied, it is an about:config setting for sure!?

---

**Comment by privacyguy123** [comment] 2022-04-26 14:57
I find it hard to reproduce myself sometimes - from what I understand digging through Virgin (ISP) forums and Reddit is that it's some short IP ban issued by Akamai (the websites CDN, also flannels.com) for reasons unknown, likely they will not share with us either. 

What's doubly strange is that their IP scoring page (https://www.akamai.com/us/en/clientrep-lookup/) reports my IP as "fine" and I can *sometimes* browse the site, but after a few clicks around while shopping like any normal person I am banned again - "default" profile in safe mode will let me click around and spam F5 without any lockout once the aforementioned IP ban times out, if I try before that I am obviously still locked out regardless of profile/addons/other.

**Comment by Onfroygmx** [comment] 2022-04-26 15:01
First: No Firefox customisation can cause a  website breakdown!
Second: Spend your 600 £ on use-full stuff.

**Comment by fxbrit** [comment] 2022-04-26 15:33
it's unlikely that a CDN would ban at the IP level over a browser configuration alone. the "Why is Akamai blocking me?" faq also seems to point to DDoS and bot detection which surely would require some volume, so unless you or someone else on your IP address (if you are NATted or behind a VPN) did something weird recently (eg. massive scrape on something hosted at akamai) I doubt they would be blocking the whole IP address, that's overkill.

since this is a server side error anyway, your best bet is to contact the website and akamai and see what's the deal. closing but feel free to keep commenting and we can re-open if new details emerge I guess.

**Closed by fxbrit** 2022-04-26 15:33 UTC

**Comment by privacyguy123** [comment] 2022-04-26 15:53
It's the only explanation I can come out with after ruling out a very long list of other things, one of which an edited user.js is currently not - I'm not saying it definitely is either.

I have ruled out anything "weird" on my connection unfortunately - it is only my laptop. phone and 2 Sky boxes on it and nothing strange showing up on virus scans and/or TCPView/Simplewall logs. Pretty stumped at this one, there is a plethora of Google results on "access denied" on Virgin and Reddit forums however, none seem to offer any kind of fix.

**Comment by privacyguy123** [comment] 2022-04-26 16:09
> Maybe some pref that changes network behaviour or ETP has any strange effect. Otherwise you can only do a binary search in the user.js to find a cause.
> 
> https://github.com/arkenfox/user.js/blob/4ff931781a1bf012e0e7e2ec89dc5c2a9bedd890/user.js#L273-L283
> 
> https://github.com/arkenfox/user.js/blob/4ff931781a1bf012e0e7e2ec89dc5c2a9bedd890/user.js#L453-L472
> 
> https://github.com/arkenfox/user.js/blob/4ff931781a1bf012e0e7e2ec89dc5c2a9bedd890/user.js#L129-L132

I've toggled all of these (except ipv6 because my ISP doesn't support it) and can still get myself blocked by Akamai 😕

**Comment by Thorin-Oakenpants** [comment] 2022-04-26 16:24
> ultimately this is a black box with a server side

I haven't tested anything, but IMO these sorts of issues are always problematic to replicate or get STR as previous tests can taint the results, i.e the server is super quick to ban your known IP than say, mine. And once an IP/range is tagged, almost anything could set it off?

**Comment by parseword** [comment] 2022-04-26 20:17
I hope it's OK to comment on a closed issue, as I wanted to provide a bit of input. I experience the same problem (see e.g. [here](https://twitter.com/parseword/status/1371273238039433219)) and I suspect this occurs because the browser isn't firing certain beacons/pixels that Akamai expects "legitimate" eyeball users to load. As a result of the beacons not being triggered, something on Akamai's end is flagging me as a bot and putting my IP into a ruleset their customers use to block "bots."

Whether this is ultimately caused by Firefox settings or DNS-level ad blocking, I haven't determined. If you want to keep digging, you might look in that direction.

**Comment by privacyguy123** [comment] 2022-04-26 20:59
Wow - appreciate your input! If you find anything more let me know - I have tried whitelisting these sites but I guess it's the underlying Akamai IPs/addresses that would need whitelisted right? Do you happen to know what they are?

**Comment by fxbrit** [comment] 2022-04-26 21:47
if you have a lead about beacon (sorry haven't read the link yet) you could try flipping `2602` and test that out.

**Comment by privacyguy123** [comment] 2022-04-26 21:54
> if you have a lead about beacon (sorry haven't read the link yet) you could try flipping `2602` and test that out.

Tried that - seems irrelevant unfortunately, but the problem is isolated to the modified FireFox environment - after some input from another Virgin user on Reddit (who can't reproduce any of this) I can rule out ISP AND dnscrypt DNS level blocking as I can reproduce getting blocked after exactly 2 clicks deep on https://www.flannels.com connected to ProtonVPN (which also bypasses anything dnscrypt is doing.) 

I'm certain we can get to the bottom of this ...

**Comment by fxbrit** [comment] 2022-04-27 09:31
sorry but this is very confusing, how is this relevant if you are not using dark reader in the first place? just like I don't see how the user.js is necessarily involved when you could reproduce it on your smartphone. 

> what on earth would this be triggering on Akamais side?

it thinks dark reader is a scraper.

**Comment by privacyguy123** [comment] 2022-04-27 10:03
> sorry but this is very confusing, how is this relevant if you are not using dark reader in the first place? just like I don't see how the user.js is necessarily involved when you could reproduce it on your smartphone.

FireFox Android supports Dark Reader. 😛 

> > what on earth would this be triggering on Akamais side?
> 
> it thinks dark reader is a scraper.

That  makes no sense to me but anyway, bug report submitted over there.
