### ISSUE TITLE
revisit: search engine region

### ISSUE THREAD

**Issue by ghost** [arkenfox/user.js#1590] opened 2022-11-21 06:48 UTC
v107 enables region tracking (`0203`) again, why?

`browser.region.network.url` is the broader setting which needs to be blocked to prevent mozilla and firefox from knowing your region (`region.current`, `region.home`, `browser.search.region`, `doh-rollout.home-region`).
`browser.region.update.enabled` is a specific setting which only controls if firefox is allowed to _switch_ `region.home`.

So `browser.region.network.url` is probably the main thing we want and not a just an additional defense-in-depth.

As firefox is now allowed to set `browser.search.region` we probably need to make `0204` active, too.

_Originally posted by @livingentity in https://github.com/arkenfox/user.js/pull/1579#discussion_r1027291580_
_Originally posted by @Thorin-Oakenpants in https://github.com/arkenfox/user.js/pull/1579#discussion_r1027378233_

**Comment by Thorin-Oakenpants** [comment] 2022-11-21 10:56
> is a specific setting which only controls if firefox is allowed to _switch_ region.home

Which is what we wanted. It's doing it's job.

> to prevent mozilla and firefox from knowing your region 

why? There's nothing wrong with the Firefox app knowing the correct region.

DoH is a roll-out based on region and you are notified and can opt out. Or you can use the pref to opt of the rollout. Besides, the rollout for en-US has been done (not that everyone will stay as en-US).

search region is already set to en-US (0203)

regional locales (intl. resolvedOptions) is for the time being only properly controllable as using en-US with 0210 + 0211 but we hope we can use RFP to enforce the same locale as the primary language (so no more mixing up en-US with en-GB, en-CA, or whatnot, and to also bypass using system formatting, which can be custom), and to make sure the primary language is not messed up (e.g. en,en-US vs en-US,en and other secondary languages)

So I fail to see what the issue is.

**Comment by Thorin-Oakenpants** [comment] 2022-11-21 11:01
> search region is already set to en-US (0203)

crap, it's inactive, sorry was looking at a different user.js

**Comment by Thorin-Oakenpants** [comment] 2022-11-21 11:29
once again ... what does the search region leak to engines?

**Comment by Thorin-Oakenpants** [comment] 2022-11-21 17:28
> So your point is that all those region based settings have no privacy value

No, they don't. The DoH one is for rollout. The regional locales is useless, we have to use en-US and prefs or wait for RFP to cover all languages. And no-one cares if Mozilla looks it up and sets it for you - they're not recording it or selling it. 

So the only one I ASKED about was search. Asked twice now. What does the search region leak to engines? Answer that. AFAICT it doesn't change the search engine, it doesn't send any extra parameters to the search engine. For example, I installed Nightly on my computer, - it was an en-US install, I think it was installed via stub and I got to choose en-US. I am NOT in the USA. But my country is `en`

```
 en-au: english (australia)
  en-be: english (belize)
  en-ca: english (canada)
  en-gb: english (united kingdom)
  en-ie: english (ireland)
  en-jm: english (jamaica)
  en-nz: english (new zealand)
  en-ph: english (philippines)
  en-tt: english (trinidad and tobago)
  en-us: english (united states)
  en-za: english (south africa)
  en-zw: english (zimbabwe)
```

And my nightly, which does not have a user.js (well a super minimal one such as sanitizing), has set my regional stuff as en-GB (for example). And the pref matches. But my search engine is still directed to `google.com`, not `google.co.uk`

So I'm asking HOW, where, when .. who, why ... does the region leak. Until I know that then what am I supposed to do.

**Comment by Thorin-Oakenpants** [comment] 2022-11-22 19:29
Sorry, to clarify ... I am asking because IDK. I don't read all of Firefox's code not have time to do so. And it's hard to test with a single machine set to a similar search region (i.e the Firrefox build is en-US and my locale is `en-somethingelse` and my OS locale is the same `en-somethingelse`, and search engine changes or region checks can take time (IIRC)

Since you seemed to know what the code does, I wanted to make sure that nothing was leaked (to a search engine) or changed on the end-user (e.g. changing their search engine)

Reopening

**Comment by afterdelight** [comment] 2022-11-26 01:50
I want to know too, how to make google search to US instead of my local country search by modifying about:config

**Comment by Thorin-Oakenpants** [comment] 2022-11-26 03:38
add a google.com search engine and set that as the default

**Comment by afterdelight** [comment] 2022-11-26 03:46
thats my default search engine and its still partially show my local language at the search results. i want it to be fully international results

**Comment by Thorin-Oakenpants** [comment] 2022-11-26 05:09
> how to make google search to US

me, add a `google.com` search engine

> thats my default search engine

So which is it. When you do a search is it using google.com?

**Comment by afterdelight** [comment] 2022-11-26 11:32
yes i was using google.com. but when i search for example 'tab session manager'. it still shows the extension page in local language. setting `browser.search.region` to `US` doesnt work. the only thing worked is to use google ncr

**Comment by fxbrit** [comment] 2022-11-26 11:37
that depends on your IP address

**Comment by Thorin-Oakenpants** [comment] 2022-11-26 13:29
> yes i was using google.com. but when i search for example 'tab session manager'. it still shows the extension page in local language. 

I asked when you search (i.e from the urlbar or the search bar) if it loads google.com - YES or NO? I'm trying to make sense of what you are saying. So you search for "tab session manager" - and you you get a bunch of results on google.com - right? WHAT page shows your locale - the google.com search results or the firefox addon page you went to from the search results? If it's the latter, then what is the url of the link from the search results - e.g. it may have a `\en-US\` or `\en-DE` path - for me it's `https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/` (and that's with my region set an en-somethingelse).

As for AMO (Addons MOzilla), there are a few things going on, but I'm going to stop there until I know what you are talking about - but one is the language you request websites to use. If you load `https://addons.mozilla.org/firefox/addon/tab-session-manager/` (without the `en-US` part) the site will redirect based on your preferred web language

And for google results, they can differ based on IP, but AFAICT they wouldn't change the preview except based on your prefered language. Are you in fact using `en-US, en`? What is the language you are seeing? What is your app language? What is your region?

**Comment by afterdelight** [comment] 2022-11-26 14:37
> yes i was using google.com.

yes i am using en-US, en and my region is ID the language im seeing is indonesia and i get `https://addons.mozilla.org/id/firefox/addon/tab-session-manager/` on search result.
what turned the search result to english is by using `https://www.google.com/?hl=en`

**Comment by Thorin-Oakenpants** [comment] 2022-11-26 16:57
> and i get https://addons.mozilla.org/id/firefox/addon/tab-session-manager/ on search result.

and six edits later - man, there is just too much noise going on

So on the search results, from google.com, the LINK is for that, right? i.e hover over the link and it right click and copy. I do NOT mean the page you end up redirected to at AMO. The snippet should be in ID because that's what the link is pointing to.

Give me a screenshot of the google.com results - the whole page. Is it in English? Or is the whole thing in ID? What if you search for something generic like "fishing" or "beer"

Open the console and type `navigator.languages` and hit enter. What does it say?

Are you in Indonesia? Are you using a VPN? Are you using any spoofing extensions? Are you using the arkenfox user.js? Did this happen in the past or has it only just started happening?

TBH, and I understand English isn't your first language, but trying to get straight answers and the right info from you is proving difficult, and honestly this is not my problem - you even said changing the search engine pref made no difference (not that I would expect it to). What I think is happening is google is using your IP to detect you are in ID and supplying some results based on that - e.g. every addon page at AMO has numerous translations

**Comment by afterdelight** [comment] 2022-11-26 17:05
no, using `https://www.google.com/?hl=en` works. so all is well now

**Comment by Thorin-Oakenpants** [comment] 2022-11-26 19:13
> no, i dont use arkenfox user.js

stop wasting my time then

**Comment by Thorin-Oakenpants** [comment] 2022-12-01 19:18
> Or does it, or can it, actually change the end target

Ahh, OK, so the pref change triggers the engine change straight away - that makes it easy to test

https://bugzilla.mozilla.org/show_bug.cgi?id=1800662#c3
> With the GB to RU switch, the issue is that we're switching from Amazon.co.uk to Amazon.com

Honestly, I do not think this is such a big deal. When you install the app, you will have a default search engine, which you can change (either install one, or whatever). If you use a built in search engine, it's going to be the one that ships with that language (I guess) and if you add one yourself it won't change

So if you are in RU but have a GB search engine (because you are en-GB on your locale), you will stick out. You should be using .com anyway. Behind a VPN? Who cares.

Annoying if you travel overseas for more than two weeks, but correct if you move countries. I am so over this.

@fxbrit should we set the search region (which I think just makes non .com users stick out, e.g. for google at least) or ignore it. I honestly don't care about DEFAULT search engines getting changed

**Comment by fxbrit** [comment] 2022-12-02 09:19
I looked some stuff up, to be clear none of this is a privacy or security thing but it's just for future reference if ever needed.

> The region is grabbed from IDK, you IP and maybe from your regional locale of the OS.

https://searchfox.org/mozilla-central/source/testing/profiles/common/user.js#28-30

so it uses a "geoip lookup" aka your IP as you rightfully guessed.

> What is the criteria for a search engine to change?

https://searchfox.org/mozilla-central/source/services/settings/dumps/main/search-config.json

this is the static dump but it can be updated via remote settings.

***

IMO this is a non-issue and we should leave it alone. most users will change their search engine (at leas the default one) and for the scope of this project the other ones do not matter; trying to match the IP with the search engine location makes little sense: we have no clue of the IP a priori, firefox is geoguessing so that could actually be a good thing as it would match the IP with the region and most importantly I would assume users trust the search engine they set as their default. if they don't then it's their interest to protect the IP.

**Comment by Thorin-Oakenpants** [comment] 2022-12-02 09:44
There are valid and good reasons to have the correct region (DoH rollout, how credit cards and addresses etc work and the rollout for that, etc). So that's not an issue. This was about search engines changing on people (after two continuous weeks) which is not likely for most users

But from OP
> `browser.region.update.enabled` is a specific setting which only controls if firefox is allowed to switch `region.home`

We should remove `0203` entirely so _everything_ works as expected. Maybe even remove `0204`

@fxbrit - are you on board to remove both?

---

> if they don't then it's their interest to protect the IP

Indeed. And a VPN _should_ "rotate" (sorry, need more coffee for the right term - am knee deep in font whackness)

>  trying to match the IP with the search engine location makes little sense

Indeed. You've chosen to use that search engine, and you already send them data about your IP (VPN ranges or not) and a bunch of search terms

**Comment by fxbrit** [comment] 2022-12-02 09:50
yup, I think we can remove both. do you want to document them for the use cause you mentioned i.e. I travel abroad I don't want my region to change every 2 weeks as a result?

> rotate

sounds super right actually 😄

**Comment by fxbrit** [comment] 2022-12-02 10:11
oops I forgot we don't have the issue with the out of scope prefs anymore.

I should check what my region has been set to here in Turks and Caicos..

**Comment by Thorin-Oakenpants** [comment] 2022-12-02 10:24
https://github.com/arkenfox/user.js/pull/1592/commits/72b8dedd411d0fba1e79215b91a771e784c52683

**Closed by Thorin-Oakenpants** 2022-12-02 10:24 UTC
Labels: enhancement
