### ISSUE TITLE
Linux GUI font affected [solved RFP/font vis]

### ISSUE THREAD

**Issue by adrian5** [arkenfox/user.js#1156] opened 2021-03-30 19:23 UTC
I noticed that using the arkenfox user.js, the UI fonts set in my OS (XFCE, font: Cantarell) are no longer getting picked up by Firefox's UI, making it look out of place. The font being used instead is fontconfig's default "sans-serif" font (DejaVu Sans).

The `privacy.resistFingerprinting` master toggle had no effect on that, nor the `[SETUP-CHROME]` related toggles I tried. Creating an empty profile without user.js creates the usual (desired) behavior.

Any idea which setting might be causing this? I imagine FF might be isolating itself more from the OS environment.

**Firefox** 87.0
**user.js** latest (87-alpha)

**Comment by adrian5** [comment] 2021-03-30 19:42
Ah yes, that's it. Thanks! I had even tried that option, but only with the example value of `1` which is not sufficient.

---

So if I insist on wanting this, I reckon I'd disable RFP? (Unless I want to set the font via userChrome.css?)

My main interest is really security, not privacy. I'm willing to trade parts of the latter for some degree of comfort. I suspect my fingerprint is absurdly unique already (Hardware, OS, FF, non-defaults), so unless I present as Chrome on Windows, it feels a losing battle.

**Comment by adrian5** [comment] 2021-03-31 22:28
I didn't have any luck with the above suggestion.

With `privacy.resistFingerprinting: true` and `layout.css.font-visibility.level` omitted (reads `3` in about:config), I placed Cantarell in what I believe to be the designated directory:

```
/usr/lib/firefox/fonts/
├── Cantarell-BoldOblique.otf
├── Cantarell-Bold.otf
├── Cantarell-Oblique.otf
├── Cantarell-Regular.otf
└── TwemojiMozilla.ttf
```

FF falls back to DejaVu Sans again. Am I missing something?

**Comment by adrian5** [comment] 2021-03-31 22:59
Do fonts I add to the above directory have to be in the set of [Linux System Fonts](https://searchfox.org/mozilla-central/source/gfx/thebes/StandardFonts-linux.inc)? If so, and e.g. non-Fedora build don't get Cantarell, then that would explain it.

**Comment by Thorin-Oakenpants** [comment] 2021-04-01 07:52
AFAIK, the fonts are populated on Firefox start: anyway,. for this exercise, a restart definitely can't hurt since we want the change to be permanent

Fonts do not have to also be in your system fonts - fixed in FF82 [1661532](https://bugzilla.mozilla.org/show_bug.cgi?id=1661532)

So what you did should work: did you set the font back to cantarell in settings?

You can read what Diego was doing [1653987 comment 12 and on](https://bugzilla.mozilla.org/show_bug.cgi?id=1653987#c12) thru to bug 1661532 .. he was using the font to set as his default web content one. Maybe the chrome UI one is used too early - I'm a little lost here. Maybe the font type needs to be tff ?

I would piggyback on [1661532](https://bugzilla.mozilla.org/show_bug.cgi?id=1661532) with your steps to reproduce and ask what's wrong - do you have a bugzilla account?

**Comment by adrian5** [comment] 2021-04-01 20:23
Yes, turns out I still had an old bugzilla account. I'll take your word that the behavior I experience is not as intended – I wouldn't have been so sure myself.

**Comment by Thorin-Oakenpants** [comment] 2021-04-01 22:11
> Setting font.system.whitelist to `Cantarell`

The whitelist needs more than one font

**Comment by Thorin-Oakenpants** [comment] 2021-04-01 22:32
hmmm .. cantarell is listed in kBaseFonts: https://searchfox.org/mozilla-central/source/gfx/thebes/StandardFonts-linux.inc#379-382 under Fedora, but not Ubuntu

I wonder what logic is used to determine which kBaseFonts to use for each linux distro. If your OS is english, perhaps you could provide Johnathon Kew a list of the default system fonts (assuming you haven't added lots and it's all a bit messy)

**Comment by adrian5** [comment] 2021-04-02 00:47
>hmmm .. cantarell is listed in kBaseFonts: https://searchfox.org/mozilla-central/source/gfx/thebes/StandardFonts- linux.inc#379-382 under Fedora, but not Ubuntu
>
> I wonder what logic is used to determine which kBaseFonts to use for each linux distro.

Didn't I already address this [earlier](https://github.com/arkenfox/user.js/issues/1156#issuecomment-811519403)?

> The whitelist needs more than one font: it should be a list to cover languages etc

Ah, I see. I assumed it would serve as an extension to the exisiting set of base fonts. It was just a workaround is stumbled upon, probably not the right preference to tackle this issue then.

> is cantarell available in your font settings?

It is, and so are all other system fonts, including non-standard ones. So Firefox at least knows of their existence (with RFP enabled).

> normally this is for the default font on web pages: chrome IDK

Yes, I'm pretty sure those settings were only ever associated with web content, not chrome.

So then, the question that remains is whether I can get Cantarell into the chrome (I don't need it on the web), or whether that functionality is fundamentally at odds with RFP in the current codebase.

**Comment by Thorin-Oakenpants** [comment] 2021-04-02 03:16
> Didn't I already address this [earlier](https://github.com/arkenfox/user.js/issues/1156#issuecomment-811519403)?

I like thinking out aloud

**Comment by Thorin-Oakenpants** [comment] 2021-04-03 15:46
In the meantime, you could set the whitelist pref to the kBaseFonts listed for either
- Fedora
- Ubuntu (but add the Cantarell ones)
- format is `name, name, name` - font name, not file name
- IDK if Xubuntu's fonts are more like Fedora or Ubuntu

Be careful with non-ascii/western? chars: e.g. don't set it from the user.js unless it's UTF-8: or you know, just manually add it to about:config

The Fedora list doesn't have any non-ascii/western chars

```js
user_pref("font.system.whitelist", "Abyssinica SIL, C059, Caladea, Cantarell, Cantarell Extra Bold, Cantarell Light, Cantarell Thin, Carlito, Comfortaa, Comfortaa Light, D050000L, DejaVu Math TeX Gyre, DejaVu Sans, DejaVu Sans Condensed, DejaVu Sans Light, DejaVu Sans Mono, DejaVu Serif, DejaVu Serif Condensed, Droid Arabic Kufi, Droid Sans, Droid Sans Armenian, Droid Sans Devanagari, Droid Sans Ethiopic, Droid Sans Fallback, Droid Sans Georgian, Droid Sans Hebrew, Droid Sans Japanese, Droid Sans Tamil, Droid Sans Thai, Jomolhari, Khmer OS, Khmer OS Content, Khmer OS System, Liberation Mono, Liberation Sans, Liberation Serif, Lohit Assamese, Lohit Bengali, Lohit Devanagari, Lohit Gujarati, Lohit Kannada, Lohit Odia, Lohit Tamil, Lohit Telugu, Meera, Mingzat, Montserrat, Montserrat Black, Montserrat ExtraBold, Montserrat ExtraLight, Montserrat Light, Montserrat Medium, Montserrat SemiBold, Montserrat Thin, Nimbus Mono PS, Nimbus Roman, Nimbus Sans, Nimbus Sans Narrow, Noto Color Emoji, Noto Sans CJK HK, Noto Sans CJK HK Black, Noto Sans CJK HK DemiLight, Noto Sans CJK HK Light, Noto Sans CJK HK Medium, Noto Sans CJK HK Thin, Noto Sans CJK JP, Noto Sans CJK JP Black, Noto Sans CJK JP DemiLight, Noto Sans CJK JP Light, Noto Sans CJK JP Medium, Noto Sans CJK JP Thin, Noto Sans CJK KR, Noto Sans CJK KR Black, Noto Sans CJK KR DemiLight, Noto Sans CJK KR Light, Noto Sans CJK KR Medium, Noto Sans CJK KR Thin, Noto Sans CJK SC, Noto Sans CJK SC Black, Noto Sans CJK SC DemiLight, Noto Sans CJK SC Light, Noto Sans CJK SC Medium, Noto Sans CJK SC Thin, Noto Sans CJK TC, Noto Sans CJK TC Black, Noto Sans CJK TC DemiLight, Noto Sans CJK TC Light, Noto Sans CJK TC Medium, Noto Sans CJK TC Thin, Noto Sans Gurmukhi, Noto Sans Mono CJK HK, Noto Sans Mono CJK JP, Noto Sans Mono CJK KR, Noto Sans Mono CJK SC, Noto Sans Mono CJK TC, Noto Sans Sinhala, Nuosu SIL, OpenSymbol, P052, Padauk, PakType Naskh Basic, PT Sans, PT Sans Narrow, Source Code Pro, Source Code Pro Black, Source Code Pro ExtraLight, Source Code Pro Light, Source Code Pro Medium, Source Code Pro Semibold, Standard Symbols PS, STIX, STIX Two Math, STIX Two Text, Symbola, URW Bookman, URW Gothic, Waree, Z003");
```

**Comment by adrian5** [comment] 2021-04-03 21:47
I've applied above Fedora list and this gives me Cantarell¹ in the chrome. Judging by a few UTF-8 test pages, rendering of non-western scripts looks to be "normal" as well (the way I'm used to without RFP), covering a lot of bases with e.g. the Noto family.

Just to confirm I'm getting this right: The idea behind these font lists is to make Firefox instances look more homogeneous among different hosts of a given OS family (Win/Mac/Linux), correct? So e.g. using the above set of fonts, I would share the base with vanilla Fedora systems.

Should I go with this for now, or do you want run further investigations? Having `font.system.whitelist` in my user-overrides.js would make this a low maintenance solution for the time being.

¹ Cantarell doesn't need to be in the FF `fonts/` directory for that

**Comment by Thorin-Oakenpants** [comment] 2021-04-03 23:23
by non-ascii/non-western chars, I meant in the pref value: because e.g. on my Windows system, the user.js file is ANSI encoded by default and characters like https://searchfox.org/mozilla-central/source/gfx/thebes/StandardFonts-linux.inc#165-170 end up as `?` in notepad++, and you would end up writing some garbage to the pref ... if I change the file's encoding to UTF-8, and re-enter/re-paste them, then they are correct: hence I said it's easier to do it manually

![ansi](https://user-images.githubusercontent.com/16656956/113493733-a7400b00-94d1-11eb-98f3-2677a32c0719.png)

> The idea behind these font lists is to make Firefox instances look more homogeneous ...

Correct. Android they haven't looked at - AFAIK all they need to do is allow Noto fonts only, and Roboto, but TBH, IDK if that would do much since IMO almost no-one adds more fonts to android devices. Windows/Mac is maybe easier- but there's still a little entropy between e.g. windows 7 and win10 users are very different, and within those two groups we (arkenfox people) found some differences (due to fonts that came with MS products like Office). Linux is harder as each distro can differ wildly. It's a hard nut to crack because the fonts need to contain enough of the right items to be able to fallback to various chars (emoji's CJK languages, Thai .. etc) otherwise you end up with tofu (hexadecimal boxes).

So at best, they can remove a lot of the entropy, but not all of it. Even Apple couldn't make all Mac users look the same, and they control the OS

**Comment by Thorin-Oakenpants** [comment] 2021-04-03 23:30
> So e.g. using the above set of fonts, I would share the base with vanilla Fedora systems. Correct?

Hopefully :)  It'll be better when they can use this for everyone [1582687](https://bugzilla.mozilla.org/show_bug.cgi?id=1582687) - I think Henri's bug popped up independently of the font vis one, but for sure they would use the same lists. RFP goes hard at level 1. This bug they are talking about a default level 2 (base plus additional language packs)

**Comment by Thorin-Oakenpants** [comment] 2021-04-04 11:10
I'll close this since you have a workaround - and upstream hopefully jfkthame can look at gating Xubuntu to the Fedora pile (assuming that's correct)

**Closed by Thorin-Oakenpants** 2021-04-04 11:10 UTC

**Comment by adrian5** [comment] 2021-04-04 20:42
Sounds good, thanks for the guidance.
