### ISSUE TITLE
[Question] About RFP

### ISSUE THREAD

**Issue by p0pcat** [arkenfox/user.js#1340] opened 2022-01-21 06:32 UTC
I found that when enabling `privacy.resistFingerprinting` it overwrites most of the set spoofing, I would like to know what does `privacy.resistFingerprinting` Enable/Disable and is there any alternatives to the features it controls?

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 07:53
> it overwrites most of the set spoofing

what set spoofing?

**Comment by Loki-L1130** [comment] 2022-01-21 09:15
@Thorin-Oakenpants This is a bit related to this. When using Spoof Timezone extension and RFP combined it actually spoofs Timezone and overrides the system Timezone and makes the selected one. But if I do disable RFP and use the extension it doesn't spoof the timezone and websites detect the original timezone flawlessly exposing.

To check the timezone I used this site : https://dev.to/aileenr/how-to-spoof-your-timezone-in-google-chrome-48ch. Please reach the end of the page.

What I am achieveing to do here is Spoofing Timezone perfecly without revealing the original Timezone in the System and without using RFP to make the spoof Timezone working.

Why I am asking is that RFP sets the User agents changes to version 91 while the current one is version 96. This makes thnings like outdated browser please use a Updated Browser or Update your Browser prompt in some websites constantly

I just want to spoof the timezone to the region exactly where I connect my VPN, so I am asking this. While Brave does this very cleverly as intended with randomized fingerprint(Which is on by default) but I want this in firefox.

I think I am clear a lot above. Could you please help me out ?

If you feel this is out of the scope of this issue, convert this comment to a new issue and mention or assign me there.

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 09:30
> While Brave does this very cleverly as intended with randomized fingerprint(Which is on by default) but I want this in firefox

Brave does no such thing. It does not protect timezones. You are confusing the purpose of fingerprinting (to never reveal the real result) vs methods to achieve that (block the API, randomize plausible values, randomize per OS, spoof the same value or lower entropy, etc) and benefits/drawbacks of each method - which depend on each metric

**Comment by Loki-L1130** [comment] 2022-01-21 09:47
@Thorin-Oakenpants I got it then what should i do achieve as I said for a complete and perfect time zone spoofing.

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 09:51
you can't - extensions lack APIs to do the job properly. people on VPNs are not expected to all have the timezone of the VPN exit point, and it wouldn't be stable from a user's viewpoint. your solution is not a solution, sorry

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 09:52
> it overwrites most of the set spoofing

closing as invalid. Firefox doesn't spoof anything by default

**Closed by Thorin-Oakenpants** 2022-01-21 09:52 UTC

**Comment by p0pcat** [comment] 2022-01-21 11:36
@Thorin-Oakenpants when settings user agent `general.useragent.override` and the `privacy.resistFingerprinting` is enabled, it will overwrite this set user agent.

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 11:59
First of all, what makes you think spoofing those is going to achieve anything? Answer: it's not, it's going to make you stand out because it can be detected, and if not directly pointed out to you by the script, then at a bare minimum it will manifest in differences with other metrics: such as having win10 fonts but claiming to be win7, or having version 96 properties but claiming to be version 91

anyway, correct - RFP ignores these (deliberately)
https://github.com/arkenfox/user.js/blob/ac0820a5dc00e04fe14fc2a74ba75e590883293c/user.js#L1253-L1258

RFP also ignores some other prefs
RFP also won't release canvas unless you allow a site exception

but generally, RFP isn't as hardened as it could be and prefs do affect it, but we hope to change that - in order to stop people fucking up the fingerprint = counterproductive

generally speaking, it is pointless to do what you are trying to do. First of all those user agent prefs are not robust and they leak. Secondly, you are not going to be able to do anything meaningful with fingerprinting here
https://github.com/arkenfox/user.js/blob/ac0820a5dc00e04fe14fc2a74ba75e590883293c/user.js#L1229-L1231

the only solution is ultimately using built-in robust browser solutions = RFP

---

the only reason to spoof these, is for web compat reasons

**Comment by Loki-L1130** [comment] 2022-01-21 12:09
@Thorin-Oakenpants I mean't to spoof the time zone to match the location of the vpn server I am connecting so that websites do not find my real location using the timezone factor. As there are timezone with only one country.

**Comment by Loki-L1130** [comment] 2022-01-21 12:13
So, Do you mean in this case I shouldn't be doing anything or Am I just making it much more complicated ?

I do not want to use RFP but be able to change timezone because RFP alters the Useragent as Popcat mentioned.  in the mean time, if i make the user agent to be the real value (latest version 96) I cannot match my timezone as GMT+0 like other RFP users.

I just want the latest version of firefox (the real user agent string) to be accessible by websites but timezones anyother than the one my Systems Use

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 12:25
> As there are timezone with only one country

that's not how timezones work. you don't look at it by country, but by .,, wait for it .. by timezone, or in this case, by TIMEZONE NAME. The fact that everywhere on earth is in a country is a coincidence

yes, I know all about timezones
- https://arkenfox.github.io/TZP/tests/timezones.html
- click the `combine years` button

```
  unique:  39 groups (>1) 141 timezones
        : 342 groups (=1) 342 timezones
   total: 381 groups .... 483 timezones
```

so yeah ... 342 timezones are unique, and you can see the long thin tail in the groups summary

> I meant to spoof the time zone to match the location of the vpn server I am connecting so that websites do not find my real location using the timezone factor

And I said, this is not how you do it. Constantly changing the timezone to match some other arbitrary value is just silly and not usable. If you want to protect your timezone then use RFP - it does not leak (extensions do)

If you want to use an extension, then you're on your own

**Comment by Loki-L1130** [comment] 2022-01-21 13:51
Great, I do understand it. I can stick to use RFP but What do you think about the Older version of Firefox as the User Agent in RFP ?

As this parcticular value makes some sites such as Disney+ which I do have a subscription says that Your Browser is Unsupported. Please download the latest version of a browser with direct links to the Installers of the Various browsers.

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 14:05
So Disney+ is unsupported in version 91? Did you enable DRM?

**Comment by Loki-L1130** [comment] 2022-01-21 14:34
Yeah, I did enabled DRM. But showing that the Browsers is outdated and please use a latest verion of the browser

**Comment by Thorin-Oakenpants** [comment] 2022-01-21 14:57
sounds like #1321

**Comment by Loki-L1130** [comment] 2022-01-21 15:13
I think we can finish this off here. I am gonna better use a separate browser without any changes just uBO and etp strict just for disney +
