### ISSUE TITLE
Firefox 89 establishes TCP connections to Google, Hetzner, Leaseweb

### ISSUE THREAD

**Issue by Just-me-ghacks** [arkenfox/user.js#1182] opened 2021-06-02 17:15 UTC
1. Upon start Firefox 89 establishes connections to remote servers (Google, Hetzner, Leaseweb) for no apparent reason (to me anyway). How to make it stop?
```
Program | Protocol | Local IP | Local Port | Remote IP | Remote Port | State
firefox.exe | TCP | 192.168.X.X | 54091 | 195.201.9.51 | 443 | ESTABLISHED
firefox.exe | TCP | 192.168.X.X | 54092 | 142.250.187.110 | 443 | ESTABLISHED
```

2. As you can expect the new Proton interface is a total disaster from ergonomics POV. Not to mention it's ugly as sh*t!

Luckily we can disable this joke (at least for now):
```
user_pref("browser.proton.enabled", false);
user_pref("browser.proton.contextmenus.enabled", false);
user_pref("browser.proton.doorhangers.enabled", false);
user_pref("browser.proton.infobars.enabled", false);
user_pref("browser.proton.modals.enabled", false);
user_pref("browser.proton.places-tooltip.enabled", false);
```
However these changes will rise entropy significantly. Is there something that can be done?

**Comment by Thorin-Oakenpants** [comment] 2021-06-02 17:55
Proton has nothing to do with entropy, and nothing to do with this repo. Using those prefs is a waste of time, they will be removed. Just mod the height if you need to with userchrome.css, install a theme of your color choices. You'll be over the slight changes within a day (where some menu items are, floaty tabs = big deal)

---

connections
- what did you change in the user.js, what extra prefs did you add in order to achieve your NO CONNECTIONS quest
- did these happen in your 88 profile? i.e are they new?
- have you ruled out all extensions: disable them all for a test
- can you reproduce reliably on every startup?
- who the F is hetzner ... never heard of them

Until **_you_** work out what the connection is for, you can't evaluate anything. If you do not care about actually evaluating a connection's purpose, but just want to kill all connections, then not my problem. AFAIConcerned, I can track and evaulate all of this via the diff changes and bugzilla. So until you come up with actual proof that a particular connection is FF default and a privacy issue, then .. not my problem

to be blunt (sorry), sorry: WTF is this obsession with killing ALL CONNECTIONS: CONNECTIONS MUST BE BAD mantra

**Comment by rusty-snake** [comment] 2021-06-02 18:21
I'll add my two cents here.
1. I haven't updated my ff so far (my distro is late this release) but looking at the diffs maybe it is `pref("signon.recipes.remoteRecipes.enabled", true);`.
2. Proton is the first redesign that makes the fox look better then before. IMHO. Maybe because I have it enabled in my nightly since it was possible (2-3 month).

**Comment by Just-me-ghacks** [comment] 2021-06-02 19:02
Doesn't browser.proton.enabled set to false change something like window size / availHeight / availWidth, etc.?

>did these happen in your 88 profile?

Firefox 88 doesn't establish any connections thanks to my custom user.js
And my hosts file looks like this:
```
127.0.0.1       content-signature-2.cdn.mozilla.net
127.0.0.1       firefox.settings.services.mozilla.com
```

>i.e are they new?

Yes, these connections have been happening since Firefox 89.
```
95.211.70.203 (AS60781 LeaseWeb Netherlands B.V.)
142.250.187.142 (AS15169 Google LLC)
```

It's not easy to work out what these connections are for. That's why I'm asking here.

>have you ruled out all extensions: disable them all for a test

I always test in FF Portable - a clean install.

>can you reproduce reliably on every startup?

Yes.

>who the F is hetzner ... never heard of them

https://en.wikipedia.org/wiki/Hetzner

**Comment by Just-me-ghacks** [comment] 2021-06-02 19:27
>maybe it is `pref("signon.recipes.remoteRecipes.enabled", true);`

Thanks for the suggestion but it's not enough:
```
firefox.exe | TCP | 192.168.1.3 | 55266 | 195.201.9.51 | 443 | ESTABLISHED
firefox.exe | TCP | 192.168.1.3 | 55267 | 142.250.187.174 | 443 | ESTABLISHED
```


>Proton is the first redesign that makes the fox look better then before.

FF88
![firefox-88](https://user-images.githubusercontent.com/25951862/120540359-21104a00-c3d8-11eb-9179-bf3c037d00e7.png)

vs

FF89 Proton
![firefox-89-proton](https://user-images.githubusercontent.com/25951862/120540376-266d9480-c3d8-11eb-9c58-e915a967e82b.png)

Not to mention the excessive padding in the bookmarks menu.

**Comment by Thorin-Oakenpants** [comment] 2021-06-02 20:02
I use nightly all the time for testing... Proton was like .. what the heck .. for about 10 minutes. Then it was just getting used to the changed menu item positions (another 10 minutes) and riding out a few tweaks as they reclaimed excessive padding .. and the dark theme on win7 [1702480](https://bugzilla.mozilla.org/show_bug.cgi?id=1702480) which was solved in 1 minute by switching to system theme (`ui.systemUsesDarkTheme` = `1` was already set)

> Doesn't browser.proton.enabled set to false change something like window size / availHeight / availWidth, etc.

themes and theme density doesn't affect anything directly (except the current window if you change it, which is not when RFP inner window size kicks in, it does that when a new window is created) - except in that it can affect padding etc, namely the toolbar. And the toolbar can affect RFP's **_new_** window size, but it seems as if the skeleton pref and other startup tweaks are picking up the changes in time to stop that now (where the inner window height would be short by a few pixels). Hard to tell since I'm only one person. RFP's letterboxing solves that anyway, so the answer is .... no, as far as web content JS is concerned

> connections

I had to check re extensions etc. Good to know you eliminated specific causes. I'll reopen this so I don't forget, because I'm interested, not because I think there is anything to worry about

**Comment by parseword** [comment] 2021-06-02 21:11
95.211.70.203 and 195.201.9.51 are (or very recently were) associated with the "Uptrends" website monitoring service, does that ring any bells?

**Comment by Thorin-Oakenpants** [comment] 2021-06-02 21:46
not seeing these on any on several firefoxs, using netmon and wireshark, and the leaseweb one sounds dodgy

all I see on my main firefox (89) are these (filtered for dns)
```
content-signature-2.cdn.mozilla.net
d2nxq2uap88usk.cloudfront.net
firefox.settings.services.mozilla.com
safebrowsing.googleapis.com
rules2.clearurls.xyz
clearurls.github.io
```

**Comment by Just-me-ghacks** [comment] 2021-06-03 03:55
1. Install Firefox Portable 89.0
2. Put your prefs.js in place.
3. Start Firefox for the first time while monitoring with CurrPorts / LiveTcpUdpWatch

If you want to see these connections again, delete the Firefox Portable 89.0 folder and start from point 1.

Thanks, **parseword**! Here is the link: https://www.uptrends.com/support/kb/account-access/ip-addresses-for-whitelisting

**Comment by Just-me-ghacks** [comment] 2021-06-03 04:38
These connections have something to do with bookmarks. FF 88.0.1 and 81.0.2 - they establish the same connections when the bookmarks toolbar is shown.

I paste my **prefs.js** and **bookmarks** in `C:\FirefoxPortable\App\DefaultData\profile`

If I don't replace the existing (empty?) bookmarks file in `C:\FirefoxPortable\App\DefaultData\profile` with my own, Firefox doesn't establish any connections.

This URL (among others) is my bookmarks file: https://www.uptrends.com/tools/uptime

How can I prevent these connections from happening while still having the opportunity to use bookmarks, export and import them?

**Comment by rusty-snake** [comment] 2021-06-03 06:12
That reminds me that my firefox has additional defult-bookmarks that I don't need/want. Therefore I do the initial start with a `NoDefaultBookmarks: true` policie (and a `ExtensionSettings` policie to install all my extensions). If I don't do this, firefox fetches the favicons of these bookmarks.

Maybe:

https://github.com/arkenfox/user.js/blob/b6d7b2bff53b1a87b8bfdbb28ba0c019eadadfbb/user.js#L605-L610

**Comment by Thorin-Oakenpants** [comment] 2021-06-03 13:59
> If you want to see these connections again, delete the Firefox Portable 89.0 folder and start from point 1

You can just delete the profile folder (FF is closed of course), and it will just create a new one .. but wait

> Install Firefox Portable 89.0, Put your prefs.js in place., Start Firefox **_for the first time_**

.. but wait ... how can you put your prefs.js in place, the profile dir does not exist yet

also, why are you copying over a prefs.js. That's a really bad idea, since the prefs contains info on things that have been done at runtime, etc .. and your new profile is now out of whack. And not everything is relative paths, and for example, the updatedir will be pointing at the old one, etc, and I think extensions break as well (except this is messed up as hell because your old dir still exists). Portable FF is not exactly perfect. Even Tor Browser breaks when moved

> Here's what you should do

- your live FF portable lives at `c:/blah/blah/FF/`
- you get a portable FFnew (e.g. 89) and install it at "c:/blah/blah/FF89/" and test it out
- you copy `c:/blah/blah/FF/` as `c:/blah/blah/FF-2021-06-03/` (I do this daily, cleaning out old ones), and I do weekly backups of stuff to an external
   - so I have a super quick way to roll back
- then you upgrade `c:/blah/blah/FF/`
   - since 84, I do this using the built in FF updater, as since FF84 portable.apps fucked up the relatives paths for some things, such as updatedir etc
   - you can also feel free to just install a new portable89 over the top
- NEVER move your portable FF location
- this way you won't have issues like missing favicons, runtime prefs all out of whack and so on, missing crlite data and more.

**Comment by Thorin-Oakenpants** [comment] 2021-06-03 14:13
> If I don't replace the existing (empty?) bookmarks file in C:\FirefoxPortable\App\DefaultData\profile with my own file, Firefox doesn't establish any connections

I do not understand this. The bookmark.html file in my portables is static, containing seven links: to FF stuff and one added for portable apps website. Bookmarks are kept in places.sqlite

This is definitely a you issue: bookmarks is not bookmarks.html, prefs.js is not meant to be thrown into new profiles, relative paths are broken (except you still have the original dir you copied from = confusion), and the way you update/migrate seems flawed

**Comment by Thorin-Oakenpants** [comment] 2021-06-03 14:27
What I suspect is that portable apps on new profiles, reads bookmarks.html to populate places on first run. This file contains hardcoded `ICON="data:image:base64:....`, so the process doesn't tries to grab favicons from the internet

If you are replacing that with your own bookmarks.html, then I'm not sure what else there is to say. That's not where bookmarks are kept.

I'm only guessing at what you're doing, and some of it doesn't make sense as I lack info. Such as populating the portable app provided bookmarks should be a one time thing only on new profiles, and after that it shouldn't happen. So is your can always reproduce limited to first run only?

If all your bookmarks are in bookmarks.html, then who put them in there, manually? Why? Are you also copying over favicons.sqlite? I'm not going to dig any deeper with guessing here, as this is not how you migrate a profile

**Comment by Just-me-ghacks** [comment] 2021-06-03 18:56
I have been using this method for years. So far so good :)

1. Install Firefox Portable
2. Delete everything in `C:\FirefoxPortable\App\Firefox\browser\features\` (extensions)
3. Delete everything **except firefox.exe** in `C:\FirefoxPortable\App\Firefox` (32bit FF)
2. Delete these files:
```
C:\FirefoxPortable\App\DefaultData\profile\bookmarks.html
C:\FirefoxPortable\App\DefaultData\profile\prefs.js
```
3. Place my own bookmarks.html and prefs.js in `C:\FirefoxPortable\App\DefaultData\profile\`
4. I start Firefox for the first time **offline** and it's already configured.
5. I then install all extensions **offline** and close the browser.
6. Archive (without compression) the folder `C:\FirefoxPortable\`
7. Run the browser and when I decide - delete it's entire folder `C:\FirefoxPortable\`
8. Extract the archive to `C:\FirefoxPortable\` to be able to run Firefox again.

bookmarks.html - I bookmarked some URLs in Firefox and then exported them to file.
prefs.js - contains lines beginning with "user_pref". Created and edited by hand.

When Mozilla release a new Firefox version I just delete `C:\FirefoxPortable\` and the archive and start from point 1.

>Are you also copying over favicons.sqlite?
No.

**Comment by Thorin-Oakenpants** [comment] 2021-06-03 21:17
step 4/5: ahh, **defaultdata**, that answers that question

Sounds like the only thing you "migrate" is some bookmarks, and you're not messing around with changed paths (and your prefs.js thing is the defaultdata one with just some entries .. which explains a lot). I'm not sure what you're trying to achieve by doing a clean vanilla each release. Just install over the top (copy or archive first for roll-back), and stop using bookmarks.html

Me, if I was you
1. copy FF portable and rename it with date: e.g. `d:\portable\FF` - copy as `d:\portable\FF-2021-06-03`
2. install portable over the top
3. remove 32bit app dire contents except firefox,exe, etc
4. open firefox, all done
5. nothing to migrate, not extensions to reinstall or configure, and your pref.js items should be in user.js as overrides if needed

Me
2. is actually using the internal update mechanism so I don't get portable apps new launcher with some broken paths

IDK why this release you're suddenly having a new profile with _your_ hack makes connections for _your_ links in _your_ modifiied bookmarks.html. Maybe something changed in the portable apps firefox launcher code, or maybe FF did something with default icons in new profiles: i mean the bookmarks.html original hardcodes the icons as data

closing as invalid

**Closed by Thorin-Oakenpants** 2021-06-03 21:17 UTC

**Comment by Just-me-ghacks** [comment] 2021-06-04 05:12
I figure it out:
```
GOOD:
<A HREF="https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/" ADD_DATE="1529952231" LAST_MODIFIED="1529952888" ICON_URI="fake-favicon-uri:https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/" ICON="data:image/png;base64,.........">uBlock Origin</A>

BAD:
<A HREF="https://www.uptrends.com/tools/uptime" ADD_DATE="1589029179" LAST_MODIFIED="1589029183" ICON_URI="https://www.uptrends.com/favicon.svg?v=4.1.935" ICON="data:image/png;base64,.........">Uptime Test</A>
```
I had two `ICON_URI="https:` entries in my bookmarks.html causing the problem.

Just edit bookmarks.html in Notepad++ and take care of any `ICON_URI="https://` entries.

This thread contains some missleading information. Pants, you should probably delete it. Otherwise, if the bookmarks.html info is considered useful, can someone please write a resume of the whole situation and edit the first post and title. Thanks!

**Comment by Thorin-Oakenpants** [comment] 2021-06-04 06:38
glad you got it sorted .. but yeah, lets trash this .. in the bin
