### ISSUE TITLE
negative x/y positions + scaling = wrong letterboxing size

### ISSUE THREAD

**Issue by thiccyoshi4568** [arkenfox/user.js#1478] opened 2022-06-14 04:17 UTC
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 101.0.1 & Windows 10 Pro
  - Steps to Reproduce (STR): Go to https://coveryourtracks.eff.org/ and test your browser. Scroll down to screen size and color depth.
  - Expected result: 1400x800x24
  - Actual result: 1400x801x24
  - Console errors and warnings:
  - Anything else you deem worth mentioning: One in x browsers have this value: 43421.4

---

**Comment by Thorin-Oakenpants** [comment] 2022-06-14 04:46
forget about the 1 in x value, the 1px height being out is the only concern here (not from arkenfox's PoV, but for RFP upstream)

report back
- what is your system scaling at
- what is your devicePixelRatio
   -  if you are not sure, turn off RFP and type `console.log(window.devicePixelRatio)` into the console
- what is the value of `layout.css.devPixelsPerPx`
- are you using any tiling managers
- what is your available screen res

**Comment by icpantsparti2** [comment] 2022-06-14 06:05
FYI just tried here, and notice:

1.
    - fresh profile with arkenfox user.js
    - re-size window so you see the letterbox padding
    - run test: https://coveryourtracks.eff.org/
    - letterbox size given as screen size ✔️

2.
    - install CanvasBlocker add-on
    - re-run test
    - window size given ❗

3.
    - in CanvasBlocker settings, untick Screen API
    - re-run test
    - letterbox size given ✔️

**Comment by Thorin-Oakenpants** [comment] 2022-06-14 06:12
Not worried about CanvasBlocker. The issue is either new window size gets thrown by 1px due to rounding because of letterboxing - see https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40081
- however, that is due to the borders (and positioning) patch that was added to Tor Browser (anchor to top, add 1px border each side, 1px border to the top)
- that's not to say that factors can't influence the new window size

It sounds like a rounding error due to subpixels / scaling

**Comment by Thorin-Oakenpants** [comment] 2022-06-14 11:36
chrome = the shiny bits that make up the web browser to hold web pages = i.e everything except the inner window/web page. People can customize it with css files to make things fatter/thinner etc. If you don't know what chrome is, I doubt you changed it

**Comment by Thorin-Oakenpants** [comment] 2022-06-14 11:44
150% - OK, that's interesting, but such a nice round figure
devicePixelRatio: 1 = that's not going to cause subpixels
layout.css.devPixelsPerPx: -1 = normal
No = no tiling mangers, good
2160x1440 = ahhh, that is your NATIVE resolution
Yes = ok, LB is on, just checking, cause is it a `new window` or a `LB` issue
no - custom chrome, good

---

Your native resolution is 2160 x 1440, but you have scaled 150%, so everything is 2/3rds the native dimensions
- so you are in effect 1440 x 960
- which is why you open at 1400 x 800

Here's the next test
- open as per usual - go to https://arkenfox.github.io/TZP/tzp.html, note inner window size (you should be 1400x801)
- now turn off letterboxing in about:config
- then go Hamburger Menu > New Window
- in the new window, go to https://arkenfox.github.io/TZP/tzp.html, what is the inner window size

This will help us know if LB is the cause

**Comment by thiccyoshi4568** [comment] 2022-06-14 11:47
Seems to be 1440 x 807 without letterboxing

**Comment by Thorin-Oakenpants** [comment] 2022-06-14 12:06
Hmm, OK. So new window is opening 7 pixels too tall

OK, repeat above. RFP + LB on as per your normal - open browser, you get 1400x801, turn LB off, open a new window, get measurement, turn LB on, get measurement. I mean LB should protect here, am intrigued if it still thinks 801 is the answer

Also, turn off RFP (just toggle it in about:config) and tell me the screen section data. I wonder if the browser itself has enough room at 960 pixels minus toolbars and chrome, isn't being forced to tile vertically

**Comment by thiccyoshi4568** [comment] 2022-06-14 12:13
Alright so, turning letterboxing on and off with RFP disabled to changes it to 807 and 801. I'll attach a screenshot of the screen info.
<img width="713" alt="Capture" src="https://user-images.githubusercontent.com/94721605/173574395-2b40aeb4-33ca-45d4-a907-e8f8f453d5f0.PNG">

**Comment by Thorin-Oakenpants** [comment] 2022-06-14 14:08
now we're talking .. this kinda smacks of https://github.com/arkenfox/user.js/issues/1277#issuecomment-987884334 where the rusty snake's chrome was taller than his screen

See the positions `-7`, `-7` ... looks like the chrome is positioned (top left coordinates) slightly offscreen. Also the scaling is subpixel at (.666667 = 2/3rds .. see, told ya) for the height (inner, mozScreenY). So that's the first two things that jump out at me

anyway, TRY this, I am intrigued. Open FF, resize the window down to IDK, like 500 x 500 and move to the middle of your screen and close. This will remove the negative starting positions in `xulstore.json`. Restart, see what happens

**Comment by thiccyoshi4568** [comment] 2022-06-14 23:48
Alright so I resized FF to 500x500, moved it to the center and restarted FF. Turns out it opened in 1400x800
<img width="1053" alt="Capture" src="https://user-images.githubusercontent.com/94721605/173707588-99e1afd8-e034-4c7d-ae09-0fc6a3259a59.PNG">.

**Comment by Thorin-Oakenpants** [comment] 2022-06-15 03:31
> Turns out it opened in 1400x800.

And if you flip RFP off, is the inner viewport still 1400x800 ?

**Comment by Thorin-Oakenpants** [comment] 2022-06-15 03:41
@tomrittervg FYI

**Comment by thiccyoshi4568** [comment] 2022-06-15 04:08
Yeah if I leave the 1400x800 window open and flip RFP off it stays the same. But if I do the 500x500 steps and restart FF with RFP off, it just stays as 500x500.

**Comment by Thorin-Oakenpants** [comment] 2022-06-15 05:03
Sorry. I meant after opening at the correct size of 1400x800 .. flip RFP and check if the new window is the same. There are two parts to this, one is new window (only happens on new window creation, like when you startup firefox), the second is letterboxing, which happens on "resize" events (and once new window has landed)

Was interested to see if the "new window" part was working (given the earlier example was 1423 x 807) - one) the width was weird and two) I wonder if the 1pixel rounding is still there.

**Comment by Thorin-Oakenpants** [comment] 2022-06-26 22:16
so much for thinking this would be easy to replicate... some notes...

Setup
- open Firefox, unmaximize, move it to the middle of your screen
- set `privacy.resistFingerprinting` to `true`
- make sure `privacy.resistFingerprinting.letterboxing` = `false` (or is not present)
- close Firefox

Control
- open Firefox, load test [1]
- expected inner window results: 1000x1000 (or rounded hundies to fit your screen/max-prefs)

Test
- close Firefox
- edit the profile's `xulstore.json` so the x/y positions are slightly offscreen
  - e.g. `"screenX":"-7","screenY":"-7",`
- open Firefox, load test [1]
- expected inner window results: ???

[1] https://arkenfox.github.io/TZP/tzp.html

---

On my windows, with devicePixelRatio at 1, DPI at 96, I cannot get the starting x/y positions to stay negatve. Not even if I use a smaller res, or split across screens, or split across screens with different resolutions, and my inner newin is always correctly rounded

Next: test with system scaling

**Comment by fxbrit** [comment] 2022-06-26 23:22
is this OS specific? macOS just goes as left/right/up/down as it can, without ever resizing the window or without going outside the desktop.

**Comment by Thorin-Oakenpants** [comment] 2022-06-26 23:32
not sure what you mean. I probably wasn't clear, after setting xulstore to use negatives, the new window uses `0, 0` or snaps to the secondary monitor top left, i.e the startup mechanism (regardless of RFP) is supposed to make the chrome all be in the window (not going to test setting heights widths larger than the screen - I only care about the x/y coordinates).

The same thing happens if I try and move the chrome outside the screen (except when moving between monitors, or you could use a rezize command in the console in an about page) - e.g. grabbing the tabstrip and pushing into negatives, it just bounces back

As for system scaling, I would want to test with something that is not an integer. But, I think this is a secondary issue (that caused LBing as a separate issue to be out by 1), and STR is something else. I mean how did OP, with no tiling manager, always get -7 etc. Is it some sort of snapping thing on his Win10?

**Comment by fxbrit** [comment] 2022-06-26 23:41
> after setting xulstore to use negatives, the new window uses 0, 0 or snaps to the secondary monitor top left

oh ok, I thought that was fucked up on windows or sum.

>  I mean how did OP, with no tiling manager, always get -7 etc. Is it some sort of snapping thing on his Win10?

my guess: he's using a secondary or external monitor. on macOS at least, the built-in display shows positive values while the external monitor shows negative values (eg. my `xulstore.json` was -1400 something for `screenX`, for testing I went -3000+).

**Comment by thiccyoshi4568** [comment] 2022-06-26 23:46
Alright so on the control I get 1400x800 and on the test I also get 1400x800. By the way, I'm not using an external monitor, only my laptop screen.

**Comment by Thorin-Oakenpants** [comment] 2022-06-26 23:52
> while the external monitor shows negative values 

would depend on your monitor's positions. Mine is primary starts at 0 and secondary starts 2561, and they're aligned to the top

> my guess: he's using a secondary or external monitor.

don't think so .. oh he's here :tada:

@thiccyoshi4568 , can you close FF, edit the `xulstore.xml` (it's just a text file) to be negatives like it used to be, i.e this bit
```
"screenX":"-7","screenY":"-7"
```

and then reopen, then reload the xulstore.xml` and see if the values changed

**Comment by Thorin-Oakenpants** [comment] 2022-06-27 00:02
fuck I need to learn to stop and read incoming ... @thiccyoshi4568 already did that, so I have my answer.

this is weird, how did OP ever get Z/Y to be negative and stay that way

**Comment by Thorin-Oakenpants** [comment] 2022-06-27 00:10
just FYI: Another way to get the window slightly offscreen, is to open a page like about:config and use the console
```
window.moveTo(-7,-7)
```

on Windows this means the OS doesn't snap it back like it did when I used my mouse. The xulstore file updates in real time. But none of this changes the result on the next restart

**Comment by fxbrit** [comment] 2022-06-27 11:53
I noticed that on my fedora 36 laptop, when I move the window to the upper-left as much as I can, TZP has a negative value for the window position (something like `-x, y, z, w`)

**Comment by fxbrit** [comment] 2022-06-27 21:46
- if it's snapped to the left corner it stays snapped and it shows the negative value once again.
- if it isn't it, brings it back to a position where the value is not negative, more centered.

I think gnome has something to do with the negative value, it looks like it uses `-26` as its `0` (at least on my machine).

**Comment by fxbrit** [comment] 2022-06-27 23:24
> in which the startup positions are negative, and when that happens it looks like RFP can't handle them

just to be clear: in the case of fedora/gnome RFP is doing a good job. even when dragging or snapping to the left corner (where the value would be negative with RFP off) it shows `0, 0, 0, 0` and letterboxing works fine. even when snapped and then closed, the window seems to be re-opening far enough from the border that it has enough space to avoid weird sizing/letterboxing issues.

I wonder how desktop env / distro specific this is.

**Comment by Thorin-Oakenpants** [comment] 2022-06-27 23:51
we need to ignore LBing (turn it off) and focus on what causes the newwin to be off. RFP spoofs the positions as `0` so you need to toggle that

**Comment by Thorin-Oakenpants** [comment] 2022-10-13 02:18
closing, this doesn't need to be tracked here, and the negative starting window position is just weird as F (and OP resolved that)

**Closed by Thorin-Oakenpants** 2022-10-13 02:18 UTC
Labels: firefox bug, fingerprinting
