### ISSUE TITLE
follow instructions or this will be closed as invalid

### ISSUE THREAD

**Issue by reslock** [arkenfox/user.js#1499] opened 2022-07-11 00:36 UTC
🟥 https://github.com/arkenfox/user.js/wiki/5.2-Troubleshooting
- [x] I have read the troubleshooting guide, done the checks and confirmed this is caused by arkenfox
   - _unchecked issues ~~may~~ will be closed as invalid_

🟪 REQUIRED INFO
  - Browser version & OS: 102.0.1 (64-bit). | Windows 11.
  - Steps to Reproduce (STR): He logged into Proton Mail, Filen, Standart Notes, Star+, HBO Max, Disney +, Movistar TV and FACEIT.
  - Expected result: The sites cookies were saved.
  - Actual result: The cookies of the sites are lost and the session is closed
  - Console errors and warnings: There are several errors in each of the pages but the one that is repeated the most is this:
![imagen](https://user-images.githubusercontent.com/107806935/178168834-dd77c918-c775-43e0-b693-f0aed2d74408.png)
  - Anything else you deem worth mentioning:
  - Before version 102 all my cookies were saved and I was never logged out of any of the mentioned sites.

---

**Comment by Thorin-Oakenpants** [comment] 2022-07-11 05:53
duplicate of #1495

**Closed by Thorin-Oakenpants** 2022-07-11 05:53 UTC
