### ISSUE TITLE
Search argument entered in url bar not passed on to Searx search engine

### ISSUE THREAD

**Issue by TommieWong** [arkenfox/user.js#1330] opened 2022-01-17 08:34 UTC
Hi,
Next issue after fixing the heightxwidth sizes (now a beautiful 1200x800!) is the search engine. 
Here is the situation:
- I use Searx as default search engine;
- In the user-overrides, I have set keyword.enabled to true;
- If I type a search argument in the URL bar in a **non-Arkenfox profile using Searx** as default search engine and hit enter, a searx page properly displays with the search results;
- If I type a search argument in the URL bar in an **Arkenfox profile using another search engine** as default and hit enter, the search engine's page properly displays with the search results;
- BUT if I type a search argument in the URL bar in an **Arkenfox profile using Searx** as default search engine and hit enter, I get the Searx homepage, blank, with no search results.
- Note: the same happens if I use the search engine icons, and not simply the default search engine.

So, on the one hand, it seems like search arguments entered in the URL bar are indeed passed on to the search engine, since this works with other search engines. So, at first glance, that seems like a Searx issue, not an Arkenfox issue.
However, using Searx on two different non-Arkenfox FF installs properly passes on the search argument to Searx, so that doesn't quite feel like a purely Searx issue either.

Any ideas?

**Comment by fxbrit** [comment] 2022-01-17 08:44
can you share the searx instance? I tried with two of them and they both work for me after flipping `keyword.enabled`.

**Comment by TommieWong** [comment] 2022-01-17 08:51
> can you share the searx instance? I tried with two of them and they both work for me after flipping `keyword.enabled`.

searx.be/

I just grabbed another one at random to try (https://searx.prvcy.eu) and it also didn't work. Care to share one that worked for you?

To be precise, when I hit enter and the Searx homepage displays, the exact URL in the bar is "https://searx.be/search", not simply "https://searx.be/".

**Comment by silverwings15** [comment] 2022-01-17 09:00
you have to go into searx preference and grab the **Search URL of the currently saved preferences**. use that instead and it will work

**Comment by fxbrit** [comment] 2022-01-17 09:33
I tested with two random instances, namely searx.be and searx.cf, which both work in my case.

what extensions do you use? any weird uBO filter list?

**Comment by TommieWong** [comment] 2022-01-17 10:08
> you have to go into searx preference and grab the **Search URL of the currently saved preferences**. use that instead and it will work

I tried removing Searx as a search engine and then re-adding it using the full URL with saved preferences, but to no avail. Same result.

> what extensions do you use? any weird uBO filter list?

uBo. Weird filter lists? I'm not sure, no. Also skip redirect, but I created an exception for Searx and it's off at the moment. In any case, I have the same extensions and the same settings in the two non-Arkenfox FF installs where the search works with Searx.

**Comment by silverwings15** [comment] 2022-01-17 10:14
1. install this addon https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/
2. go into its setting and install the searx engine like so
![image](https://user-images.githubusercontent.com/10742312/149750702-34cd9a5e-3c1f-47d0-b80f-1931c91e6e6c.png)
3. follow rest of instruction, then go into mozilla search settings to give it a keyword

**Comment by fxbrit** [comment] 2022-01-17 10:21
@silverwings15 he shouldn't do all of this to get it to work, I just went to [searx.be](https://searx.be), right clicked on the urlbar and then clicked on add "searx belgium".

@TommieWong can you
- create a new clean profile
- apply the latest user.js
- revert `keyword.enabled`
- add searx as I said above
- re-test

I just can't reproduce this on my end.

**Comment by TommieWong** [comment] 2022-01-17 10:40
> I just can't reproduce this on my end.
Done. It works like that (and without having to use the long URL with preferences).
That new profile doesn't have my usual extensions; on the other hand, on my regular profile, deactivating uBO doesn't help either.

**Comment by fxbrit** [comment] 2022-01-17 10:48
> That new profile doesn't have my usual extensions

I tried with both uBO (I even activated all the default lists and added _actually legitimate url shortener_) and skip redirect installed, and it still worked for me. I would suggesting enabling your extensions one by one in that new clean profile to see which one is causing problems, but at least we know the issue is also not related to the user.js on your end.

**Comment by fxbrit** [comment] 2022-01-17 10:51
@Thorin-Oakenpants I think you can close this. if we want to find out what's breaking searx we can do it in the closed issue or elsewhere.

**Comment by silverwings15** [comment] 2022-01-17 11:01
> @silverwings15 he shouldn't do all of this to get it to work

true, i forgot to mention the benefit of using my method is so that he can configure the search engine settings to his liking and use those instead. but if he is satisfied with the defaults then it is indeed too much work

**Comment by TommieWong** [comment] 2022-01-17 11:19
Found the guilty add-on/setting: automatic mode in Temporary Containers. When disabled, the passing of search arguments works. This seems linked to the way Searx performs its searches (no utm parameters, no cookies, etc.), which is why it doesn't affect DDG for instance.

However, this doesn't entirely explain why Searx works with Temporary Containers in automatic mode in a non-Arkenfox profile, but not using the user.js. So it may not really be the user.js' fault, but it's not without an impact either.

**Closed** 2022-01-17 11:38 UTC

**Comment by fxbrit** [comment] 2022-01-17 12:02
sorry but why haven't you mentioned you are using TC when I asked about extensions? :-|

> turns out that, even with automatic mode activated, if I am already on a Searx results page and then search using Searx from the URL bar, then the search works.

yes, because automatic mode opens a container for each new tab basically, but if you stay in that tab then it re-uses the container and it works. it's probably easy to fix this but I don't think it's worth changing anything in the user.js just to use an extension that brings zero benefits to the table when using dFPI. just get rid of TC imo.

**Comment by Thorin-Oakenpants** [comment] 2022-01-17 12:18
When I finish replacing the entire wiki I am going to have to make sure troubleshooting highlights the very first thing to do is to make sure you can
- not have the issue in a new profile (thus proving it is not a FF bug)
- replicate the issue in that new profile with AF applied (proving that is is AF)
- ^^ that is no old prefs, no prefs left un-reset, no extensions

**Comment by TommieWong** [comment] 2022-01-17 12:39
> sorry but why haven't you mentioned you are using TC when I asked about extensions? :-|

Sorry, my bad. I hardly notice it anymore. I guess it also didn't feel like a likely candidate for the error, since the search works with it in non-Arkenfox profiles. 

> it's probably easy to fix this but I don't think it's worth changing anything in the user.js just to use an extension that brings zero benefits to the table when using dFPI. just get rid of TC imo.

If you have a minute to spare, I'd still be interested in a way to fix it. We can PM instead of writing here. 

I've been weighing the pros and cons of the extension, and for now I have chosen to keep it. I usually use my FF for very long stretches of time, so I like the possibility to sanitise in session -- even though, yes, I've read the wiki's mention of that being a false sense of security, since it does nothing for IP tracking; I don't consider it the same as sanitise on close, but to me it's better than nothing when I leave the browser open for days.

**Comment by fxbrit** [comment] 2022-01-17 13:29
> If you have a minute to spare

when launching **stock firefox** or opening a new tab in it, TP immediately creates a container so when you search you already are inside a container.

if you use **arkenfox** new windows and new tab pages are set to `about:blank`, and in that case TP fails to create a new container for some reason. when you search tho, it creates the container but the search cannot be passed to it so it fails to actually display the result.

**Comment by TommieWong** [comment] 2022-01-17 13:37
@fxbrit Thanks for the explanation. Did a quick search and that's addressed here: https://github.com/stoically/temporary-containers/issues/332
